### ISSUE TITLE
PubSub: custom retry settings don't work with Cloud Functions

### ISSUE THREAD

**Issue by gmdev** [googleapis/python-pubsub#10]
I have a Cloud Function triggered by Pub/Sub and I would like to configure custom retry times as specified in the following docs:

https://cloud.google.com/functions/docs/bestpractices/retries
https://cloud.google.com/pubsub/docs/publisher#retry

Here is the code:

```python
from google.cloud.pubsub_v1 import PublisherClient

retry_settings = {
    'interfaces': {
        'google.pubsub.v1.Publisher': {
            'retry_params': {
                'messaging': {'initial_retry_delay_millis': 30000},
                'default': {'initial_retry_delay_millis': 30000},
            }
        }
    }
}

PubSubPublisher(
    publisher=PublisherClient(client_config=retry_settings),
    project_id='some_project',
)
```

Retry is enabled for the subscriber (`--retry` flag passed on deploy). We are using `python37` runtime.

The problem is, while it merges the configs properly, it doesn't seem to actually apply the configuration. The retry delay seems to be still the default 100ms.

One thing that I suspect may be the issue here is that Python libs only allow configuring the delay for `messaging` and not `streaming_messaging` (as `retry_params_def ` seen here: https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub_gapic.yaml ). I might be wrong, but If Google Cloud Functions use Streaming Pull, this would likely be the cause.

Potential solution: allow configuring `streaming_messaging` in `retry_params`.

**Comment by paul1319** [comment]
@gmdev , could you clarify, where would you like to configure custom retry in publisher, subscriber or cloud function? And where would you like to have opportunity to configure `streaming_messaging`?

**Comment by gmdev** [comment]
@paul1319 I think this is actually a missing feature in Pub/Sub itself.

What I was looking for initially is to have a way of letting Pub/Sub know it should not retry triggering the Cloud Function every 100ms if the CF returns an error. This is way too aggressive in many cases.

What I didn't understand initially is that the config in my first post here relates to the Publisher retries (how often the client code should retry publishing the message to the topic if the operation fails for whatever reason) and not Subscriber retries (how often the subscription message delivery should be retried if the push operation fails).

AFAIK the latter is simply not possible currently with Pub/Sub and Cloud Tasks are recommended instead (https://cloud.google.com/pubsub/docs/tasks-vs-pubsub#detailed-feature-comparison).

**Comment by kamalaboulhosn** [comment]
Having control over retry delay on the subscriber is not currently supported in Cloud Pub/Sub, you are correct. It is a feature we are looking to add, though.

**Comment by pradn** [comment]
The [API](https://github.com/googleapis/googleapis/blob/48a166ce9f6e2a88b10947341b37336fe9dd3478/google/pubsub/v1/pubsub.proto#L707) for RetryPolicy has been made public, so you will soon be able to control the retry delay.

**Comment by gmdev** [comment]
That's great news! 👍

**Comment by pradn** [comment]
I'm closing this as RetryPolicy is close to being released publicly.
