### ISSUE TITLE
Inaccurate Dosctrings in Modules: `google/pubsub_v1/services/subscriber`

### ISSUE THREAD

**Issue by gentris** [googleapis/python-pubsub#1020]
### Summary
Several functions within the following modules are affected by misleading docstrings, which may result in confusion for users seeking to understand the behavior of these functions.

The affected modules include:

- google/pubsub_v1/services/subscriber/async_client.py
- google/pubsub_v1/services/subscriber/client.py
- google/pubsub_v1/services/subscriber/transports/grpc.py
- google/pubsub_v1/services/subscriber/transports/grpc_asyncio.py

### Details
The issue primarily revolves around the incorrect usage of the term "returns" in the docstrings for certain functions, specifically when describing their behavior during exceptional circumstances. In these cases, the functions are expected to raise exceptions such as `ALREADY_EXISTS` and `NOT_FOUND` instead of returning these exceptions.

This inconsistency between the docstring descriptions and the actual behavior of the functions can lead to misunderstandings, potentially impacting the usability and reliability of the codebase.

### Proposed Solution
The recommended solution is to update the docstrings in the affected modules to accurately reflect the behavior of these functions. This correction will enhance the clarity and correctness of the documentation, making it easier for users to comprehend the expected behavior of the functions during edge cases.

**Comment by pradn** [comment]
Hey @gentris, good catch. An example of such a mistake is [here](https://github.com/googleapis/python-pubsub/blob/653b983bbaa4e7b4202c24b4aaf261132a874cf5/google/pubsub_v1/services/subscriber/async_client.py#L242). These files are auto-generated, so I'll have to look into where I can fix these.

As an aside, did the docstrings come up via your IDE or were you looking at the files directly?

**Comment by gentris** [comment]
Hey @pradn, I read the documentation (docstrings) directly in the file. But even now, using the **PyCharm** IDE for example,  it's displayed as `returns` instead of `raises`. See the attached screenshot.
<img width="766" alt="Screenshot 2023-11-06 at 3 19 22 PM" src="https://github.com/googleapis/python-pubsub/assets/27731903/da816b42-198f-4370-8edf-cb17de6985da">

**Comment by pradn** [comment]
Okay, I see. That's helpful.

Thank you for taking the time to write up #1021, but we can't merge it because it's modifying auto-generated code. Your changes will be overridden in the next generation step. We would need to modify the [CPS API definition proto file](https://github.com/googleapis/googleapis/blob/01ebb1901fae079b01d0a41035d01fa52035391c/google/pubsub/v1/pubsub.proto#L433) upsteam. But first, we're going to discuss internally and see.

**Comment by pradn** [comment]
I know this is a problem, but we're going to hold off on making changes for now. There's quite a lot of similar wording for CPS APIs and also for other GCP products. We'd want to consider a wider solution, perhaps one that tailors wording per library. Thank you for filing the issue.
