### ISSUE TITLE
snippet to check for no messages

### ISSUE THREAD

**Issue by kthulsidoss** [googleapis/python-pubsub#104]
Hello ,

I'm using synchronous pull , there is need to check if there are no message and then process
response = subscriber.pull(subscription_path, max_messages=NUM_MESSAGES)

so how to check if there are no messages received ? can we check the length

e.g 
if len(response) < 1: 
sleep for some time
else
do the processing()

**Comment by IlyaFaer** [comment]
@kthulsidoss, according to [the official sample for a synchronous pull](https://cloud.google.com/pubsub/docs/pull#synchronous_pull), you can use such a command:
```python
if len(response.received_messages):
    {process messages}
```

**Comment by kthulsidoss** [comment]
**@IlyaFaer**  kind of you ,also i reffered to the stack over flow here https://stackoverflow.com/questions/58321230/google-cloud-pubsub-python-synchronous-pull for the initial confirmation

**Comment by kthulsidoss** [comment]
by the way the creator could have thought of doing it in C# way  in python too ... need a requirement request ?
/ allowing an immediate response if there are no messages.
PullResponse response = subscriberClient.Pull(
    subscriptionName, returnImmediately: true, maxMessages: 20);

**Comment by IlyaFaer** [comment]
@kthulsidoss, samples live in the [samples repository](https://github.com/GoogleCloudPlatform/python-docs-samples/issues), let's open an issue there and see what responsible googlers will say. There is an `return_immediately` arg in Python `pull()` method as well, so it's not gonna be difficult to do this.
