### ISSUE TITLE
unused message arg in Batch.will_accept()

### ISSUE THREAD

**Issue by IlyaFaer** [googleapis/python-pubsub#105]
Looks like `message` arg is never used by `will_accept()` method:
https://github.com/googleapis/python-pubsub/blob/cf9e87c80c0771f3fa6ef784a8d76cb760ad37ef/google/cloud/pubsub_v1/publisher/_batch/base.py#L112-L136

Most likely it should be deleted to avoid any confusion, but I suppose it should be done with deprecation. `Batch()` is not something pretending to be manually used by users, but who knows.

@pradn, please, comment

**Comment by pradn** [comment]
will_accept is unnecessary, and partially duplicates the checks done in [thread.Batch.publish](https://github.com/googleapis/python-pubsub/blob/cf9e87c80c0771f3fa6ef784a8d76cb760ad37ef/google/cloud/pubsub_v1/publisher/_batch/thread.py#L355). We should just incorporate it into publish().

I don't think people rely on being able to override Batch. We have made a bunch of changes to Batch that they would have to keep up with, so it's not advisable anyway. So it should be fine to just modify the interface without deprecation.
