### ISSUE TITLE
message.nack() will that remove the message from the topic

### ISSUE THREAD

**Issue by kthulsidoss** [googleapis/python-pubsub#106]
Hello

Greetings. This is a question on negating the acknowledge .. let us say we want to negate the acknowledge meaning we want pub sub to remove the message from topi itself , so based on certain condition will this work
message.nack()
Thanks
**K.Thulsi Doss**

**Comment by pradn** [comment]
Each subscription gets a copy of all the messages published to a topic. Acks and nacks modify the set of messages a subscription, not a topic, is holding on to. So, there's no way to ack/nack a message to a topic, which would mean it would be acked/nacked to all its subscriptions.

**Comment by plamut** [comment]
Closing this issue, as the question has been answered.

@kthulsidoss If you think more clarification is needed, feel free to revisit this thread and let us know how we can help.
