### ISSUE TITLE
Opt-in Trace Context Propagation

### ISSUE THREAD

**Issue by AlexCasF** [googleapis/python-pubsub#1286]
## Feature Description
Add support for opt-in trace context propagation in the Python PubSub client, allowing users to maintain distributed tracing across async message boundaries when appropriate.

## Use Case
When building distributed systems with multiple microservices communicating via PubSub, there are scenarios where maintaining trace context across async boundaries is valuable:
- Workflow tracking where messages are part of a sequential process
- Debugging specific message flows
- Service-to-service communication where maintaining context is important

## Proposed Solution
Add new options to "PublisherOptions":

```
class PublisherOptions:
enable_trace_propagation: bool = False # Default to False
trace_propagation_mode: TracePropagationMode = TracePropagationMode.METADATA
```

The client could then handle trace context propagation at the transport layer rather than requiring users to manually add trace context as message attributes - which works for continuing the trace with the subscribing microservice, but will lead to a new empty trace being created in parallel.

## Important Considerations
- Opt-in by default to avoid unexpected behavior in fan-out/fan-in scenarios
- Clear documentation about appropriate use cases
- Performance implications should be documented
- Complexity warnings for fan-out/fan-in scenarios

## Additional context
This feature would align with OpenTelemetry best practices while respecting the unique challenges of async communication patterns.

**Comment by mukund-ananthu** [comment]
@hongalex fyi

**Comment by mukund-ananthu** [comment]
Closing due to no response. Feel free to reopen.
