### ISSUE TITLE
PubSub: Implement SubscriberClient.get_snapshot method

### ISSUE THREAD

**Issue by ostrokach** [googleapis/python-pubsub#13]
**Is your feature request related to a problem? Please describe.**

I need to make sure that a specific topic, subscription, and snapshot have already been created. In the case of topic and subscription, I can do something like:

```python
try:
    _ = pub_client.get_topic(self.location)
    _ = sub_client.get_subscription(self.subscription_path)
except NotFound:
    ...
```

However, in the case of snapshot, I have to do something like:

```python
snapshot_exists = False
for element in sub_client.list_snapshots(project):
    if element.name == "snapshot_name":
        snapshot_exists = True
```
which is both inelegant and inefficient.

 **Describe the solution you'd like**

I would like the PubSub `SubscriberClient` to have a `.get_snapshot(...)` method. There seems to be a [`GetSnapshotRequest`](https://cloud.google.com/pubsub/docs/reference/rest/v1/GetSnapshotRequest) endpoint, so I am not sure why this method is not available? 

 **Describe alternatives you've considered**

See the code snippet above.

 **Additional context**

**Comment by pradn** [comment]
I'm working on changing the visibility labels for GetSnapshot and GetTopicSnapshots.

**Comment by pradn** [comment]
The [change](https://github.com/googleapis/googleapis/commit/3d5d228a58bdf875e6147b228db3159010c735ee) to the gapic config has been committed. This issue should be fixed once the libraries are regenerated.

**Comment by plamut** [comment]
The `get_snapshot()` method has been added [here](https://github.com/googleapis/python-pubsub/pull/66/files#diff-dc6c81a4d4f6d5a3436ce56b4d7ca507R771), we can close the issue now.
