### ISSUE TITLE
Publish Future done_callback never called.

### ISSUE THREAD

**Issue by dboshardy** [googleapis/python-pubsub#142]
#### Environment details
Docker:
`python:3.8-buster`

```
pip3 freeze


cachetools==4.1.0
certifi==2020.4.5.2
chardet==3.0.4
click==7.1.2
Flask==1.1.2
gevent==20.6.2
google-api-core==1.20.1
google-auth==1.17.2
google-cloud-bigquery==1.25.0
google-cloud-core==1.3.0
google-cloud-pubsub==1.6.0
google-resumable-media==0.5.1
googleapis-common-protos==1.52.0
greenlet==0.4.16
grpc-google-iam-v1==0.12.3
grpcio==1.29.0
gunicorn==20.0.4
idna==2.9
itsdangerous==1.1.0
Jinja2==2.11.2
MarkupSafe==1.1.1
protobuf==3.12.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pytz==2020.1
requests==2.23.0
rsa==4.6
six==1.15.0
urllib3==1.25.9
Werkzeug==1.0.1
zope.event==4.4
zope.interface==5.1.0
```

#### Steps to reproduce

  1. Publish a large volume of messages across several clients.
  2. Wait/sleep to resolve the futures using the [model provided in Google Documentation examples](https://cloud.google.com/pubsub/docs/publisher#publishing_messages)
  3. Some requests hang indefinitely as the future never cancels or resolves.

There is nothing I can see in the logs that show any error.  We are implementing an exponential backoff instead of infinite while loop with a retry added in.  But this seems like something that should eventually cancel.

**Comment by pradn** [comment]
1. Are you using publisher-side flow control? If not, try using it and see how it goes. [In-progress docs](https://github.com/googleapis/python-pubsub/pull/129/files).
2. How long are you waiting for the timeouts?
3. Can you check to see if your messages have been successfully published to CPS? You can subscribe from a subscription on the topic and count the number of messages published to the topic. This will help us narrow down what sort of client issue this may be.

**Comment by dboshardy** [comment]
> Are you using publisher-side flow control? If not, try using it and see how it goes. In-progress docs.
Yes with default settings for the limits.
> How long are you waiting for the timeouts?
Typically hours.

It's unclear if they're being published or not, the message count is ultimately not what it should be.

On our side implementing an exponential backoff instead of sleeping indefinitely and then retrying the outstanding message publication and this resolves the issue 100% of the time.

**Comment by pradn** [comment]
To clarify, are you using the [newly introduced](https://github.com/googleapis/python-pubsub/blob/04e261c602a2919cc75b3efa3dab099fb2cf704c/google/cloud/pubsub_v1/publisher/client.py#L100) publisher flow control feature, or the older "batch_settings" setting?

**Comment by dboshardy** [comment]
We're using `PublisherFlowControl` and `BatchSettings`.  This is our init:

```python
publisher = pubsub_v1.PublisherClient(
        publisher_options=pubsub_v1.types.PublisherOptions(
            flow_control=pubsub_v1.types.PublishFlowControl(
                limit_exceeded_behavior=pubsub_v1.types.LimitExceededBehavior.BLOCK,
                message_limit=batch_size * 10,
                byte_limit=max_bytes * 10
            ),
            enable_message_ordering=False
        ),
        batch_settings=pubsub_v1.types.BatchSettings(
            max_messages=batch_size,
            max_bytes=max_bytes
        ),
        client_config={
            "interfaces": {
                "google.pubsub.v1.Publisher": {
                    "retry_params": {
                        "messaging": {
                            'total_timeout_millis': 60000 * 2,  # default: 600000
                        }
                    }
                }
            }
        },

    )
```

**Comment by plamut** [comment]
@dboshardy All messages are routed through the flow controller, and no errors in the logs could indicate that they get stuck there indefinitely - either due to a bug in the flow controller itself, or because the publish futures never resolve and never free up the capacity in the flow controller (a message is removed from the flow controller when the corresponding publish future is resolved with either success or error).

Could you perhaps change the logging level to DEBUG and check if there are any threads blocking indefinitely? ([example message](https://github.com/googleapis/python-pubsub/blob/cfe486afa7a051e019486d87250fa069886868c5/google/cloud/pubsub_v1/publisher/flow_controller.py#L140-L143) without the corresponding [wake up message](https://github.com/googleapis/python-pubsub/blob/cfe486afa7a051e019486d87250fa069886868c5/google/cloud/pubsub_v1/publisher/flow_controller.py#L147-L150)). Do you see anything suspicious in the load information in these messages?

By the way, is the publisher client instance shared between multiple threads (processes), or do you use a separate instance for each thread (process)?

The client should be thread safe, but there might an edge case that we don't yet know about.

**Comment by dboshardy** [comment]
@plamut We ended up with a workaround by retrying the publish. Let me check with the project lead to see if we can make time to test this.

> Could you perhaps change the logging level to DEBUG and check if there are any threads blocking indefinitely? (example message without the corresponding wake up message). Do you see anything suspicious in the load information in these messages?

I was checking logs around this time and didn't see any flow control messages one way or the other.

> By the way, is the publisher client instance shared between multiple threads (processes), or do you use a separate instance for each thread (process)?

It's shared across threads (gunicorn with preload and gthread workers).

**Comment by plamut** [comment]
> I was checking logs around this time and didn't see any flow control messages one way or the other.

Hmm, now that's really odd. Perhaps the client gets stuck somewhere else and not in the flow controller...

> It's shared across threads (gunicorn with preload and gthread workers).

Just as a sanity check, would it be feasible to change the setup to **not** use a shared client instance, say, in a staging environment, and see if the problem disappears? And does the same happen if some other flow control mode is used, e.g. ERROR?
