### ISSUE TITLE
Pub/Sub: double definitions for lots of class properties

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/python-pubsub#15]
The [documentation](https://googleapis.github.io/google-cloud-python/latest/pubsub/types.html#google.cloud.pubsub_v1.types.AcknowledgeRequest) for `pubsub_v1.types` shows lots of double definitions: a true definition, plus one that just says `field ....`.

**Comment by meredithslota** [comment]
@anguillanneuf Can you give more information? I can't repro this based on the description. Possibly obsolete?

**Comment by anguillanneuf** [comment]
@meredithslota This issue isn't obsolete. As shown in the screenshot, `subscription` and `ack_id` are defined twice in `AcknowledgementRequest`.

<img width="700" alt="Screen Shot 2020-03-16 at 9 30 45 AM" src="https://user-images.githubusercontent.com/9518298/76779764-1d5bbd80-6769-11ea-82cc-9f8d770ecf0f.png">

**Comment by anguillanneuf** [comment]
It looks like other API documentation, e.g. [`google-cloud-vision`](https://googleapis.dev/python/vision/latest/gapic/v1p2beta1/types.html), also has the same double-definition format. Closing.
