### ISSUE TITLE
Ability To Update Subscription Retry Policy

### ISSUE THREAD

**Issue by rholloway** [googleapis/python-pubsub#161]
Currently it doesn't seem like there is a way to update a subscription to use the new RetryPolicy via python library, or at the very least if it is possible it's certainly not clear or documented.

I was able to create a new subscription using the client, although there wasn't any documentation around this either. Below is a code snippet after I did a little digging to figure out the right format to use the new retry_policy parameter on create_subscription()
```

from google.cloud import pubsub_v1
minimum = pubsub_v1.types.Duration().FromSeconds(60)
maximum = pubsub_v1.types.Duration().FromSeconds(600)
retry_policy = pubsub_v1.types.RetryPolicy(minimum_backoff=minimum, maximum_backoff=maximum)
pubsub_v1.SubscriberClient().create_subscription(subscription_path, topic_path, retry_policy=retry_policy)

```

Note it seemed a little odd and different given the process for configuring flow control actually expects integers, rather than some protobuf object. I originally expected to be able to specify integers here as well but it did not work.

Regardless of that, I was unable to find a way to update the subscription. If it is possible using existing code (even if a little messy) and someone knows, I'd be curious to know until there is a function such as modify_retry_policy() that could be used...

**Comment by plamut** [comment]
@rholloway The documentation for subscriber client methods can be found in the client library reference documentation, e.g. [create_subscription()](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.create_subscription) method. Updating the retry policy should be possible through the [update_subscription()](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.update_subscription) method by providing modified `RetryPolicy` settings.

Does this help with your problem?

Re: flow control settings - this is not a type created from a protobuf definition, but instead a hand-written type [implemented](https://github.com/googleapis/python-pubsub/blob/b1bfc9e7ae540fed4a5ae81f9d895072a255a15d/google/cloud/pubsub_v1/types.py#L123-L143) as a namedtuple, hence the difference.

**Comment by fbukevin** [comment]
> @rholloway The documentation for subscriber client methods can be found in the client library reference documentation, e.g. [create_subscription()](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.create_subscription) method. Updating the retry policy should be possible through the [update_subscription()](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.update_subscription) method by providing modified `RetryPolicy` settings.

I'm using google-cloud-pubsub version 2.9.0.
While I invoking `create_subscription`, the `retry` parameter is not RetryPolicy but `Union[google.api_core.retry.Retry`.
And even I set up with an object of `Union[google.api_core.retry.Retry`, the retry policy of the subscription does not apply.
