### ISSUE TITLE
Feature to nack a message for delayed redelivery

### ISSUE THREAD

**Issue by itsparser** [googleapis/python-pubsub#169]
**Is your feature request related to a problem? Please describe.** 
1. Receive a message
2. Decide that the message cannot be processed yet
3. Don't want to block flow control by delaying before nacking
4. Find yourself frustrated

 **Describe the solution you'd like**
  Ref - [pub-sub-node.js-255](https://github.com/googleapis/nodejs-pubsub/issues/255)

The suggestion there of adding an optional delay parameter to the nack method.

**Comment by plamut** [comment]
This sounds like retry policy that can be configured when e.g.  creating a subscription ([docs](https://googleapis.dev/python/pubsub/latest/subscriber/api/client.html#google.cloud.pubsub_v1.subscriber.client.Client.create_subscription)).

By default the server tries to re-deliver nack-ed messages as soon as possible, but with a custom retry policy, message re-delivery can be delayed.

Would that help with your use case?

**Comment by itsparser** [comment]
@plamut  thanks for documents and response , I have gone through this feature already, the problem is Maximum delay between consecutive deliveries of a given message are as following 

> Value should be between 0 and 600 seconds. Defaults to 600 seconds.

If i like to have custom retry policy with exponential interval or custom interval 
i can't do this with pub/sub retry policy - since it capped to 600 secs

let say i have custom interval as following 

> 10min - 1hr - 5hrs - 24hrs - 2days -  Dead lettering

Since this interval can't be done thought the above retry 

nack a message for delayed redelivery - help to handle both the custom interval and any exponential interval since the control with be with user

**Comment by plamut** [comment]
If I understand correctly, you would like to have an option to configure custom re-delivery intervals? I'll check if that can be (or is planned to be) supported on the backend. One thing to note is that there might be architectural limits on what the maximum possible/feasible re-delivery delay is.

@kamalaboulhosn Could you provide more insight into what the backend supports? Is it currently even possible to configure custom re-delivery patterns such as the one mentioned above?
> 10min - 1hr - 5hrs - 24hrs - 2days - Dead lettering

**Comment by pradn** [comment]
We don't currently support the sequence you want above.

You can combine a RetryPolicy with a DeadLetterPolicy. You'd get exponential backoff from RetryPolicy, and after some set number of failures, the message would be dead-lettered. Note that both features are best-effort, but generally work pretty well.

The longest backoff duration that you can specify is 600 seconds. So, that's one reason why we can't support the sequence you mention. The other is that RetryPolicy only lets you set an exponential backoff policy with your chosen min/max timeouts. (No custom sequence support exists.)

**Comment by hongalex** [comment]
Closing this issue based on the suggestion that @pradn suggested.
