### ISSUE TITLE
Async pull performance understanding

### ISSUE THREAD

**Issue by mitzkia** [googleapis/python-pubsub#174]
I would ask a help, to understand why `async pull` is much slower than `sync pull` in our environments.
And if it is possible how can we speed up `async pull` performance?

About our setup:
- The PubSub endpoint is the native GCP endpoint
- There is 1 topic with 1 connected subscription
- Topic is filled with messages which are 100 bytes each
- Mainly Python scripts are from: https://cloud.google.com/pubsub/docs/pull
- Clients are on-premise Ubuntu systems
- We are using Python3

Performance measurements:
1, `async pull` with 1 thread: ~1800 messages/sec
2, `async pull` with 12 threads (with help of threading.Thread module): ~7000 messages/sec
3, `async pull` with 1 ThreadPoolExecutor worker (with ThreadScheduler and FlowControl): ~2000 messages/sec
4, `async pull` with 12 ThreadPoolExecutor worker (with ThreadScheduler and FlowControl): ~2000 messages/sec

compared to
5, `sync pull` with 1 threads (with help of threading.Thread module): ~3800 messages/sec
6, `sync pull` with 12 threads (with help of threading.Thread module): ~26000 messages/sec

What is your experience with async performance, how fast can it be in a non GCP environment (where the client is on-premise)?

Thanks for you help.

**Comment by mitzkia** [comment]
If it helps I can share an output for `async pull` where logging was enabled.

**Comment by plamut** [comment]
@mitzkia Would you mind sharing the details on how you created the threads? Did you run the entire linked sample code in a separate thread or was the client instance shared among them? Did you use a custom scheduler to dispatch the messages to callbacks?

The sync pull pulls the messages from the subscription, while the async pull automatically does the same in the background, but with some additional processing and bookkeeping, which causes some overhead. If subscription is filled up with messages, then simply pulling them could be faster, because each `pull` request will fetch a lot of messages with little additional overhead.

Streaming pull uses a thread pool to asynchronously dispatch received messages to the user callback, and the default pool size is 10. This means that there are at most 10 messages dispatched at a time, while the rest need to wait until one of the callbacks is done processing (by (N)ACK-ing a message) and a thread is released - it could be that this was the bottleneck in your case.

Can you reproduce the same if the topic is not pre-filled with messages, and messages are instead published on the fly at irregular intervals? Or with larger messages? Streaming pull should perform well in this setup, as it will receive the messages as soon as they are available, while the sync pull might actually poll too (in)frequently for optimal performance.

It's hard to say for certain without additional info, but I hope you got some pointers on what to focus on in the benchmark setup.

**Comment by mitzkia** [comment]
@plamut Thanks for your answer and explanations. For now I did not have too much time, but later today or tomorrow I will answer to your questions.

**Comment by mitzkia** [comment]
Sorry for the late answer.

- Since from my first comment, I have combined threading.Thread module with ThreadPoolExecutor, and when I run it with 10 threads and with 10 workers for each I could reach 10000 messages/sec at the end of the fetching, this was the top for me.
- My other experience is the performance is wavy for async (why is this happening?):
  - during one perf measurement: +- 1000 messages / sec 
  - between different perf measurements: +- 1000 messages / sec 
- Previously I have run the same measurement for messages with 1000 bytes, at the end the performance was a little bit worse 
- Could you please measure the performance in your environment maybe for a 60 sec interval (just to exclude is not it an environment issue in our side)?

- Sample code for async pull with threading.Thread modules (thread numbers can define from command line, with start argument):
```python
subscriber = pubsub_v1.SubscriberClient()
subscription_path = subscriber.subscription_path(project_id, subscription_id)

received = 0
t0 = time.time()


def pull_messages_async(project_id, subscription_id, finish_timeout):
    global received, t0

    def callback(message):
        global received, t0
        message.ack()
        received += 1
        if received == 1:
            print("first message data: {}".format(message.data))
        if received % 100 == 0:
            t1 = time.time()
            elapsed = t1 - t0
            print("elapsed time: {} received: {}; {} msg/sec".format(int(elapsed), received, received / elapsed))

    streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
    print("Listening for messages on {}..\n".format(subscription_path))

    with subscriber:
        try:
            streaming_pull_future.result(timeout=finish_timeout)
        except TimeoutError:
            streaming_pull_future.cancel()


def start_threads(thread_counter, finish_timeout):
    threads = []
    for i in range(1, thread_counter + 1):
        t = threading.Thread(target=pull_messages_async, args=(project_id, subscription_id, finish_timeout))
        threads.append(t)
        t.start()
    for t in threads:
        t.join()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--thread-counter', default=4, type=int, help='Specify number of threads')
    parser.add_argument('--finish-timeout', default=60, type=int, help='Sepcify number of sec after perf measurement should exit')

    args = parser.parse_args()

    print("Current thread counter: {}, finish timeout: {}".format(args.thread_counter, args.finish_timeout))
    start_threads(args.thread_counter, args.finish_timeout)
```

- Sample code for async pull with ThreadPoolExecutor and with FlowControl (max messages for FlowControl was always 1000)

```python
ctr = 0
t0 = time.time()


def run_perf(message_limit_for_flow_control, thread_pool_executor, finish_timeout):
    project_id = "secret-data"
    subscription_id = "secret-data"

    # Number of seconds the subscriber should listen for messages
    timeout = finish_timeout

    subscriber = pubsub_v1.SubscriberClient()
    # The `subscription_path` method creates a fully qualified identifier
    # in the form `projects/{project_id}/subscriptions/{subscription_id}`
    subscription_path = subscriber.subscription_path(project_id, subscription_id)
    flow_control = pubsub_v1.types.FlowControl(max_messages=message_limit_for_flow_control)
    scheduler = ThreadScheduler(concurrent.futures.thread.ThreadPoolExecutor(thread_pool_executor))

    def callback(message):
        global ctr, t0
        message.ack()
        ctr += 1
        if ctr % 100 == 0:
            t1 = time.time()
            elapsed = t1 - t0
            print("elapsed time: {} received: {}; {} msg/sec".format(int(elapsed), ctr, ctr/elapsed))

    streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback, scheduler=scheduler, flow_control=flow_control)
    print("Listening for messages on {}..\n".format(subscription_path))

    # Wrap subscriber in a 'with' block to automatically call close() when done.
    with subscriber:
        try:
            # When `timeout` is not set, result() will block indefinitely,
            # unless an exception is encountered first.
            streaming_pull_future.result(timeout=timeout)
        except TimeoutError:
            streaming_pull_future.cancel()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--message-limit-for-flow-control', default=1000, type=int, help='Max messages for FlowControl')
    parser.add_argument('--thread-pool-executor', default=1, type=int, help='Number of ThreadPool executors')
    parser.add_argument('--finish-timeout', default=60, type=int, help='Sepcify number of sec after perf measurement should exit')

    args = parser.parse_args()

    print("Message limit for flow control: {}".format(args.message_limit_for_flow_control))
    print("Thread pool executor number: {}".format(args.thread_pool_executor))
    print("Finish timeout: {}".format(args.finish_timeout))

    run_perf(args.message_limit_for_flow_control, args.thread_pool_executor, args.finish_timeout)
```

**Comment by plamut** [comment]
@mitzkia Thanks for the samples and additional measurements. I'm mostly offline this week, but can have a closer look when I'm back.

Currently the primary focus is to [transition](https://github.com/googleapis/python-pubsub/pull/158) the library to the new code generator and drop Python 2 support, which is a breaking change and might affect the library's performance. It thus probably make sense to wait with more detailed measurements until after this transition has been completed.

**Comment by mitzkia** [comment]
@plamut Ok, thanks for your answer.

**Comment by plamut** [comment]
Just for the reference, a new major version has been released, and the observed figures might be different now.

I will probably not have time to dive into this in the near future, though, my apologies.

**Comment by mitzkia** [comment]
@plamut Sorry for the late answer. 
Thanks for your answer. Since than I am working on an other task. 
Hopefully later I can test the new release. Until then I am closing this.

Thanks.

**Comment by redbullsxtra** [comment]
> I would ask a help, to understand why `async pull` is much slower than `sync pull` in our environments.
> And if it is possible how can we speed up `async pull` performance?
> 
> About our setup:
> 
> * The PubSub endpoint is the native GCP endpoint
> * There is 1 topic with 1 connected subscription
> * Topic is filled with messages which are 100 bytes each
> * Mainly Python scripts are from: https://cloud.google.com/pubsub/docs/pull
> * Clients are on-premise Ubuntu systems
> * We are using Python3
> 
> Performance measurements:
> 1, `async pull` with 1 thread: ~1800 messages/sec
> 2, `async pull` with 12 threads (with help of threading.Thread module): ~7000 messages/sec
> 3, `async pull` with 1 ThreadPoolExecutor worker (with ThreadScheduler and FlowControl): ~2000 messages/sec
> 4, `async pull` with 12 ThreadPoolExecutor worker (with ThreadScheduler and FlowControl): ~2000 messages/sec
> 
> compared to
> 5, `sync pull` with 1 threads (with help of threading.Thread module): ~3800 messages/sec
> 6, `sync pull` with 12 threads (with help of threading.Thread module): ~26000 messages/sec
> 
> What is your experience with async performance, how fast can it be in a non GCP environment (where the client is on-premise)?
> 
> Thanks for you help.



> Sorry for the late answer.
> 
> * Since from my first comment, I have combined threading.Thread module with ThreadPoolExecutor, and when I run it with 10 threads and with 10 workers for each I could reach 10000 messages/sec at the end of the fetching, this was the top for me.
> * My other experience is the performance is wavy for async (why is this happening?):
>   
>   * during one perf measurement: +- 1000 messages / sec
>   * between different perf measurements: +- 1000 messages / sec
> * Previously I have run the same measurement for messages with 1000 bytes, at the end the performance was a little bit worse
> * Could you please measure the performance in your environment maybe for a 60 sec interval (just to exclude it is not an environment issue in our side)?
> * Sample code for async pull with threading.Thread modules (thread numbers can define from command line, with start argument):
> 
> ```python
> subscriber = pubsub_v1.SubscriberClient()
> subscription_path = subscriber.subscription_path(project_id, subscription_id)
> 
> received = 0
> t0 = time.time()
> 
> 
> def pull_messages_async(project_id, subscription_id, finish_timeout):
>     global received, t0
> 
>     def callback(message):
>         global received, t0
>         message.ack()
>         received += 1
>         if received == 1:
>             print("first message data: {}".format(message.data))
>         if received % 100 == 0:
>             t1 = time.time()
>             elapsed = t1 - t0
>             print("elapsed time: {} received: {}; {} msg/sec".format(int(elapsed), received, received / elapsed))
> 
>     streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback)
>     print("Listening for messages on {}..\n".format(subscription_path))
> 
>     with subscriber:
>         try:
>             streaming_pull_future.result(timeout=finish_timeout)
>         except TimeoutError:
>             streaming_pull_future.cancel()
> 
> 
> def start_threads(thread_counter, finish_timeout):
>     threads = []
>     for i in range(1, thread_counter + 1):
>         t = threading.Thread(target=pull_messages_async, args=(project_id, subscription_id, finish_timeout))
>         threads.append(t)
>         t.start()
>     for t in threads:
>         t.join()
> 
> 
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--thread-counter', default=4, type=int, help='Specify number of threads')
>     parser.add_argument('--finish-timeout', default=60, type=int, help='Sepcify number of sec after perf measurement should exit')
> 
>     args = parser.parse_args()
> 
>     print("Current thread counter: {}, finish timeout: {}".format(args.thread_counter, args.finish_timeout))
>     start_threads(args.thread_counter, args.finish_timeout)
> ```
> 
> * Sample code for async pull with ThreadPoolExecutor and with FlowControl (max messages for FlowControl was always 1000)
> 
> ```python
> ctr = 0
> t0 = time.time()
> 
> 
> def run_perf(message_limit_for_flow_control, thread_pool_executor, finish_timeout):
>     project_id = "secret-data"
>     subscription_id = "secret-data"
> 
>     # Number of seconds the subscriber should listen for messages
>     timeout = finish_timeout
> 
>     subscriber = pubsub_v1.SubscriberClient()
>     # The `subscription_path` method creates a fully qualified identifier
>     # in the form `projects/{project_id}/subscriptions/{subscription_id}`
>     subscription_path = subscriber.subscription_path(project_id, subscription_id)
>     flow_control = pubsub_v1.types.FlowControl(max_messages=message_limit_for_flow_control)
>     scheduler = ThreadScheduler(concurrent.futures.thread.ThreadPoolExecutor(thread_pool_executor))
> 
>     def callback(message):
>         global ctr, t0
>         message.ack()
>         ctr += 1
>         if ctr % 100 == 0:
>             t1 = time.time()
>             elapsed = t1 - t0
>             print("elapsed time: {} received: {}; {} msg/sec".format(int(elapsed), ctr, ctr/elapsed))
> 
>     streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback, scheduler=scheduler, flow_control=flow_control)
>     print("Listening for messages on {}..\n".format(subscription_path))
> 
>     # Wrap subscriber in a 'with' block to automatically call close() when done.
>     with subscriber:
>         try:
>             # When `timeout` is not set, result() will block indefinitely,
>             # unless an exception is encountered first.
>             streaming_pull_future.result(timeout=timeout)
>         except TimeoutError:
>             streaming_pull_future.cancel()
> 
> 
> def main():
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--message-limit-for-flow-control', default=1000, type=int, help='Max messages for FlowControl')
>     parser.add_argument('--thread-pool-executor', default=1, type=int, help='Number of ThreadPool executors')
>     parser.add_argument('--finish-timeout', default=60, type=int, help='Sepcify number of sec after perf measurement should exit')
> 
>     args = parser.parse_args()
> 
>     print("Message limit for flow control: {}".format(args.message_limit_for_flow_control))
>     print("Thread pool executor number: {}".format(args.thread_pool_executor))
>     print("Finish timeout: {}".format(args.finish_timeout))
> 
>     run_perf(args.message_limit_for_flow_control, args.thread_pool_executor, args.finish_timeout)
> ```

Hi mitzkia

Would it be possible to share snippet code of "sync pull with 12 threads" how did you do that ? I would like to do some performance testing as well.
