### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by pradn** [googleapis/python-pubsub#178]
These two are pretty consistently flaky.

test_publisher_client.py::test_wait_and_commit_sequencers
test_publisher_client.py::test_stopped_client_does_not_commit_sequencers

**Comment by plamut** [comment]
@pradn These two are unit tests, what error(s) do they occasionally fail with?

**Comment by plamut** [comment]
TL; DR - I had quite some trouble reproducing this, but was eventually able to observe the failure.

In one of the runs I got the error `PermissionDenied: 403 The request is missing a valid API key`, which made me think that the unit test actually tries to contact the backend. When I then switched from a superfast wired connection to a (still quite fast) WiFi, the failures became much more common, although the latter might be a coincidence.
