### ISSUE TITLE
Got an unexpected keyword argument 'request' on create_topic

### ISSUE THREAD

**Issue by arnoe** [googleapis/python-pubsub#182]
#### Environment details

  - OS type and version: macOS High Sierra 10.13.6 (17G9016)
  - Python version: `Python 3.8.5`
  - pip version: `pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)`
  - `google-cloud-pubsub` version: 
```
Name: google-cloud-pubsub
Version: 1.6.1
Summary: Google Cloud Pub/Sub API client library
Home-page: https://github.com/googleapis/python-pubsub
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /private/tmp/python-pubsub/samples/snippets/pubsub/lib/python3.8/site-packages
Requires: grpc-google-iam-v1, google-api-core
Required-by: (pubsub) 
```

#### Steps to reproduce
```
git clone --depth=1 git@github.com:googleapis/python-pubsub.git /tmp/python-pubsub
set -e
cd /tmp/python-pubsub/samples/snippets
pip install virtualenv
virtualenv pubsub
source pubsub/bin/activate
export PUBSUB_EMULATOR_HOST=0.0.0.0:****
export PUBSUB_PROJECT_ID=****
pip install -r requirements.txt
python publisher.py ***** create *****
```

#### Stack trace
```
Traceback (most recent call last):
  File "publisher.py", line 404, in <module>
    create_topic(args.project_id, args.topic_id)
  File "publisher.py", line 56, in create_topic
    topic = publisher.create_topic(request={"name": topic_path})
  File "/private/tmp/python-pubsub/samples/snippets/pubsub/lib/python3.8/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
TypeError: create_topic() got an unexpected keyword argument 'request'
```

Thanks!

**Comment by plamut** [comment]
@arnoe It appears that you are running the _very latest_ version of the samples, but with not-the-very-latest PubSub client installed. Yesterday a [pull request](https://github.com/googleapis/python-pubsub/pull/158) was merged that brought breaking changes to the library, and it will be released as version 2.0 in the near future.

In other words, the `request` argument in the following call:
```py
topic = publisher.create_topic(request={"name": topic_path})
```
... will only become available once the new major version of the client is released.

I can see that the script clones the repository and runs the cutting edge version of the samples, which are now ahead of any PubSub versions released to date.

The quickest solution is probably to clone the release branch that matches the PubSub version installed, i.e. 1.6.1:
```
git clone --depth 1 --branch v1.6.1 git@github.com:googleapis/python-pubsub.git /tmp/python-pubsub
```

**Comment by mbrancato** [comment]
@plamut - I hit this error as well, in other methods. It might be prudent to check why the official docs (link below) are using a syntax that is not yet released. Maybe the docs are autoloading from GitHub but should instead pull from a released tag?

https://cloud.google.com/pubsub/docs/pull#synchronous_pull_with_lease_management

**Comment by plamut** [comment]
> I hit this error as well, in other methods. 

True, this is expected, as the autogenerated parts of the library have changed quite a bit.

The samples docs indeed shouldn't have been updated yet, at least not until the release, thanks for ringing this to attention!

@anguillanneuf Is there a way to "block" the samples from updating automatically and only update them once the changes in the commits have actually been _released_? (and not merely merged)

**Comment by anguillanneuf** [comment]
@plamut No, the refresh on samples is automatic. We can revert the samples and specify a different requirement for samples testing. Or we should release the library asap.

**Comment by plamut** [comment]
I see... we might want to update the process so that samples are not updated before the corresponding code is released.

I'm all for the release, but currently awaiting confirmation.

**Comment by anguillanneuf** [comment]
Sounds good, I was expecting the release to quickly follow after the release. 

Let's coordinate better next time if we expect a gap between a merge and a new release where samples will change. I can ask the tech writer if they can pause the automatic refresh on samples beforehand.

**Comment by RonanT-cubyn** [comment]
Quickest way for me : 
I "fix" it by replacing line 55 
`topic = publisher.create_topic(request={"name": topic_path})`
by 
`topic = publisher.create_topic(topic_path)`

**Comment by plamut** [comment]
@RonanT-cubyn Indeed, that's the old form, thanks for posting it here!

Also, as an update, the new major version of the library will be released on Monday, which will bring the released code up to date with the updated samples in the docs.

@anguillanneuf 
his got me thinking... is the old samples code still available anywhere for the people who will not upgrade the client to the new major version immediately, and will want to use the `1.7.0` version for some time?

Though on the other hand, those people already know how to use the library, and new users should just use the 2.x version that will not support Python 2 anymore...

**Comment by plamut** [comment]
This issue should be resolved once #189 is published.

(a tag has already been created, now waiting for the release bot to actually publish the library to PyPI)

**Comment by plamut** [comment]
The new version has been [published](https://pypi.org/project/google-cloud-pubsub/#history), it's just that the bot did not post any notifications on the release PR. The samples should work now again.

**Comment by anguillanneuf** [comment]
@plamut Some old samples should still be available in the [documentation](https://googleapis.dev/python/pubsub/1.7.0/index.html) for <2.0.0.

**Comment by plamut** [comment]
@anguillanneuf That's great!

Although the same cannot be said for the samples on [cloud.google.com/pubsub](https://cloud.google.com/pubsub/docs/admin), right? It's only possible for the client library reference docs?
