### ISSUE TITLE
PublisherClient methods no longer supporting previous way of calling

### ISSUE THREAD

**Issue by sli2126** [googleapis/python-pubsub#194]
It looks like methods no longer take topic name/path as an unnamed arg, causing test failures in Python Logging and Storage clients:
https://source.cloud.google.com/results/invocations/a5ade010-9ee5-463b-ad2e-6e106badb197/targets
https://source.cloud.google.com/results/invocations/44fbcc26-bb84-421d-bbca-fee58f6df1c2/targets

#### Steps to reproduce

  1. Run tests/system/test_system.py in python-logging or python-storage.

#### Code example

```python
publisher = pubsub_v1.PublisherClient()
publisher.create_topic(topic_path)
```

#### Stack trace
```
.nox/system-3-6/lib/python3.6/site-packages/google/cloud/pubsub_v1/_gapic.py:40: in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
.nox/system-3-6/lib/python3.6/site-packages/google/pubsub_v1/services/publisher/client.py:310: in create_topic
    request = pubsub.Topic(request)
```

**Comment by plamut** [comment]
@sli2126 I presume you are talking about the new major version released a few days ago, i.e. `2.0.0`?

Your observation is correct, as the major version introduced several breaking changes, dropped Python 2.7 and 3.5 support, etc. - the [UPGRADING](https://github.com/googleapis/python-pubsub/blob/v2.0.0/UPGRADING.md) guide explains the differences.

As for the failing tests, the libraries should pin the PubSub dependency to `<2.0.0dev` until the code is adjusted.

**Comment by sli2126** [comment]
Understood, thanks for the quick response!
