### ISSUE TITLE
docs have incorrect example for v2.0.0

### ISSUE THREAD

**Issue by rvandegrift** [googleapis/python-pubsub#198]
The examples in the documentation have not been updated for the changes described in [1].

[1] https://googleapis.dev/python/pubsub/latest/UPGRADING.html

**Comment by plamut** [comment]
@rvandegrift Which examples are you referring to, the one in the [product documentation](https://cloud.google.com/pubsub/docs/overview) or in the [library reference](https://googleapis.dev/python/pubsub/latest/index.html)?

We'll happily fix that, thanks for the report!

**Comment by rvandegrift** [comment]
@plamut the library reference - sorry, I meant to include a link to the one that threw me off yesterday.  It's here: https://googleapis.dev/python/pubsub/latest/subscriber/index.html#pulling-a-subscription-synchronously
