### ISSUE TITLE
Auto generated code get_distribution method through `DistributionNotFound` error

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-pubsub#200]
Try statement never executed because of `get_distribution(google-pubsub)`, it should be get_distribution("google-cloud-pubsub",)
https://github.com/googleapis/python-pubsub/blob/6b9eec81ccee81ab93646eaf7652139fc218ed36/google/pubsub_v1/services/publisher/transports/base.py#L34-L37

also found same thing at various places:
https://github.com/googleapis/python-pubsub/blob/6b9eec81ccee81ab93646eaf7652139fc218ed36/google/pubsub_v1/services/subscriber/transports/base.py#L36

https://github.com/googleapis/python-pubsub/blob/6b9eec81ccee81ab93646eaf7652139fc218ed36/google/pubsub_v1/services/publisher/async_client.py#L1093

https://github.com/googleapis/python-pubsub/blob/6b9eec81ccee81ab93646eaf7652139fc218ed36/google/pubsub_v1/services/publisher/client.py#L1199

https://github.com/googleapis/python-pubsub/blob/6b9eec81ccee81ab93646eaf7652139fc218ed36/google/pubsub_v1/services/subscriber/client.py#L1904

**Comment by plamut** [comment]
@cguardia This might be another one to get started, feel free to assign yourself if you have capacity.

**Comment by meredithslota** [comment]
Is this an issue with the code generator or something that should be fixed in the handwritten layers? cc: @anguillanneuf

**Comment by anguillanneuf** [comment]
The file structure looks a bit off. Why do we have `pubsub` and `pubsub_v1` nested twice?

This is what we have currently.

```
- google 
  - cloud
     - pubsub
     - pubsub_v`
     - __init__.py
  - pubsub
  - pubsub_v1
  - __init__.py
```
This is what we should have?

```
- google
  - cloud
     - pubsub
     - pubsub_v`
     - __init__.py
```

I referenced https://github.com/googleapis/python-vision/tree/master/google.

**Comment by plamut** [comment]
@anguillanneuf `google/cloud/*` is the hand-written code, while the code in `google/pubsub` and `google/pubsub_v1` is generated by the microgenerator.

I don't remember exactly why this is the case, it might have been the most straightforward way to avoid any conflicts between the generated code and the hand-written code during the transition to the microgenerator. We might want to refactor this at some point, though, and configure thegenerator to generate the code under `google/cloud/pubsub[_v1]` to avoid confusion.

**Comment by plamut** [comment]
Looking at the [ClientInfo docstring](https://github.com/googleapis/python-api-core/blob/30211b4a8c6a1979ed9c67c129792ccd80128b45/google/api_core/client_info.py#L48-L53), `gapic_version` should be used for `gapic-generated` libraries. On the other hand, libraries that implement additional features on top the generated code should use the `client_library_version` argument (which is what `get_distribution("google-cloud-pubsub")` would return).

We can modify these pieces of generated code and provide the client library version, I'm sure the server-side analytics would benefit from it. If there's no setting in the generator itself, we can still do it through `synth.py`.

**Comment by anguillanneuf** [comment]
Thanks Peter for the link to ClientInfo docstring! Sounds like we should go with `client_library_version = pkg_resources.get_distribution("google-cloud-pubsub",).version`.
