### ISSUE TITLE
KeyError: 'messageRetentionDuration' when creating a new subscription.

### ISSUE THREAD

**Issue by avargaslugo** [googleapis/python-pubsub#213]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-pubsub/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: **10.15.6**
  - Python version: `python --version`: **Python 3.7.5**
  - pip version: `pip --version`: **pip 20.2.2**
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub`:  **Version: 2.1.0**

#### Steps to reproduce

  1. define a request dictionary to create a subscription; make sure to define the `messageRetentionDuration` field.
  2. create subscription using `SubscriberClient`
  3. If the field  `messageRetentionDuration` is removed the subscription is created successfully.

#### Code example

```python
# create subscriber client
subscriber = pubsub_v1.SubscriberClient()
# define request dictionary
request = {
        "name": SUBSCRIPTION_PATH, # valid subscription path
        "topic": TOPIC_PATH, # valid topic path
        "messageRetentionDuration": f"{message_retention_seconds}s", # message_retention_seconds=3600 in my case
        "ackDeadlineSeconds": ack_deadline_seconds, # ack_deadline_seconds=30 in my case
    }

subscriber.create_subscription(request=request)
```

#### Stack trace
```
# example
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/Users/avargaslugo/cryptosage/cryptosage-execution-traders/tests/execution_trader_tests.py", line 62, in test_xt_traders_from_request
    trader.execute_trade()
  File "/Users/avargaslugo/cryptosage/cryptosage-execution-traders/source/traderabc.py", line 105, in execute_trade
    filtering=filtering)
  File "/Users/avargaslugo/cryptosage/cryptosage-execution-traders/source/utils.py", line 81, in create_subscription_if_needed
    if SUBSCRIPTION_PATH not in subscriptions:
  File "/Users/avargaslugo/cryptosage/cryptosage-execution-traders/venv/lib/python3.7/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/Users/avargaslugo/cryptosage/cryptosage-execution-traders/venv/lib/python3.7/site-packages/google/pubsub_v1/services/subscriber/client.py", line 412, in create_subscription
    request = pubsub.Subscription(request)
  File "/Users/avargaslugo/cryptosage/cryptosage-execution-traders/venv/lib/python3.7/site-packages/proto/message.py", line 425, in __init__
    pb_type = self._meta.fields[key].pb_type
KeyError: 'messageRetentionDuration'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by HemangChothani** [comment]
@avargaslugo Yes i think those are changed. please verify for  `messageRetentionDuration` and  `ackDeadlineSeconds`
https://github.com/googleapis/python-pubsub/blob/7228f6c9a4c050bf22bb4bc3582b89b04eaa8702/google/pubsub_v1/types/pubsub.py#L442

 https://github.com/googleapis/python-pubsub/blob/7228f6c9a4c050bf22bb4bc3582b89b04eaa8702/google/pubsub_v1/types/pubsub.py#L472

**Comment by avargaslugo** [comment]
@HemangChothani , thanks for your prompt reply. `ack_deadline_seconds` works well in my case, it's defined as an int. Does that mean that the field `messageRetentionDuration` needs to be a `duration.Duration`?  I tried the following request using a `Duration` object and am getting the same exception

```python
subscriber = pubsub_v1.SubscriberClient()

duration = Duration()
duration.FromSeconds(3600)

request = {
        "name": SUBSCRIPTION_PATH,
        "topic": TOPIC_PATH,
        "filter": filtering,
        "messageRetentionDuration": duration,
        "ackDeadlineSeconds": 30
    }

subscriber.create_subscription(request=request)
```

**Comment by HemangChothani** [comment]
@avargaslugo I think  like  this `"message_retention_duration": {"seconds": 911},` it will work.

**Comment by avargaslugo** [comment]
That worked! thanks a lot!
