### ISSUE TITLE
Sample snippets are failing due to requirements

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-pubsub#215]
requiremnts.txt file has `google-cloud-pubsub==1.6.1` dependency, sample needs min version `google-cloud-pubsub==2.0.0`

https://github.com/googleapis/python-pubsub/blob/7228f6c9a4c050bf22bb4bc3582b89b04eaa8702/samples/snippets/requirements.txt#L1

**Comment by HemangChothani** [comment]
@plamut Do we need to update `requirements.txt` file in https://github.com/renovate-bot/python-asset/blob/master/samples/snippets/requirements.txt repo or we can do in the `google-cloud-pubsub` (same) repo.

**Comment by plamut** [comment]
@HemangChothani Yes, the samples have been updated to work with PubSub 2.0.0, thus feel free to bump the version in `requirements.txt`.

(BTW, I will not be working on Google cloud libraries in Q4, @cguardia will back me up in the meantime)
