### ISSUE TITLE
Pubsub: allow registering a callback for batches of messages.

### ISSUE THREAD

**Issue by gcbirzan** [googleapis/python-pubsub#22]
The old API allowed you to operate on batches of messages. Sometimes, this is advantageous as you can aggregate other calls. With the current API, this is non trivial.

So, I think (if the underlying code supports it), adding, either a parameter to open(), or another function open_many() that'll always return a list (there could be a limit in the flow control), even if it's just with one item would be useful.

**Comment by plamut** [comment]
@hongalex Reviving this for consideration - would it make sense to add this feature?

Back then the PR was not merged, because consistency across clients for various languages would have been violated, but perhaps this is something we might still want to implement?

**Comment by kamalaboulhosn** [comment]
@plamut  The issue with adding this API is that we don't necessarily treat a batch that was published as a single entity. Therefore, the user can't expect to receive messages published as a single batch in a single batch in the client. Therefore, having a batch receive API could be confusing.

**Comment by plamut** [comment]
Hmm... a valid point indeed.

**Comment by pradn** [comment]
I'm going to close this issue because we don't plan on implementing this in the forseeable future.
