### ISSUE TITLE
fixup_pubsub_v1_keywords.py changes publisher.publish which results in TypeError

### ISSUE THREAD

**Issue by teije01** [googleapis/python-pubsub#228]
## Environment details

  - OS type and version: `Linux teije-dell 5.8.16-2-MANJARO #1 SMP PREEMPT Mon Oct 19 11:33:03 UTC 2020 x86_64 GNU/Linux`
  - Python version: `Python 3.6.11`
  - pip version: `pip 20.2.3`
  - `google-cloud-pubsub` version: `2.1.0`

#### Code example

Running `fixup_pubsub_v1_keywords.py` on a script that includes
```python
from google.cloud import pubsub

publisher = pubsub.PublisherClient()
publisher.publish(topic, message)
```
changes that into

```python
from google.cloud import pubsub

publisher = pubsub.PublisherClient()
publisher.publish(request = {'topic': topic_path, 'messages': message})
```

#### Stack trace

Invoking the new style `request` results in
```
TypeError: publish() missing 2 required positional arguments: 'topic' and 'data'
```

**Comment by cguardia** [comment]
Hi, @teije01 you are correct that the script has this problem on version 2.1.0. This is fixed on current master, but the new release has not been made yet.

**Comment by teije01** [comment]
I see, that's why I could not find an open issue, it was already closed. Thanks for the clarification.
