### ISSUE TITLE
Not able to send messages in a job queue

### ISSUE THREAD

**Issue by adityaprakash-bobby** [googleapis/python-pubsub#229]
Hi, I am facing a weird issue with pubsub python client. I am running a django client with a redis job queue for long running processes. I earlier used to call the publish method from the pubsub client outside of the job queue, it used to publish the messages to the pubsub queue, but once I moved the same piece of code to the job queue logic, the whole logic worked except for the pubsub client not publishing the message, neither throwing any exception in the logs. I followed [this example](https://cloud.google.com/pubsub/docs/publisher#publishing_messages) from the documentation by adding a callback, but there was no change in the behaviour. It was giving out the result (`future.result()`) but won't publish the message. Am I making some mistake here? Some idea on this will be helpful

#### Environment details

  - OS type and version: 18.04.1-Ubuntu x86_64 GNU/Linux
  - Python version: Python 3.6.9
  - pip version: pip 20.1.1
  - `google-cloud-pubsub` version: 1.6.1

#### Steps to reproduce

  1. Call the below function from anywhere.
  2. Next, call the exact same function from within a job queue. (I use `django-rq` for this)

#### Code example

```python
# example
def _get_callback(f, data):
    def callback(f):
        try:
            slogger.glob.info("Pubsub result: {}".format(f.result()))
        except:
            slogger.glob.warn('Please handle {} for {}.'.format(f.exception(), data))
    return callback

def _publish_to_pubsub(message, topic, project_id):
    topic_name = publish_client.topic_path(project_id, topic)
    future = publish_client.publish(topic_name, message)
    future.add_done_callback(_get_callback(future, str(message)))
```

#### Stack trace
```
# None
```

Thanks!

**Comment by anguillanneuf** [comment]
@adityaprakash-bobby What made you say that your code failed to publish? If `future.result()` successfully prints message IDs, your message is received by the Pub/Sub server.

**Comment by adityaprakash-bobby** [comment]
Thanks for getting back.
@anguillanneuf Once I publish the message, it triggers an app engine, but I did not see the message in the logs for app engine processing it. Just to be sure, I had created a pull subscription to check if I got any on the messages, but there were none. 

My bad, `f.result()` inside the callback (`_get_callback`) prints the message. To make it work, I had to explicitly make a blocking call to `future.result()` at the end of `_publish_to_pubsub`. Is there some reason it won't work inside a job queue without the explicit call to `future.result()`?

**Comment by anguillanneuf** [comment]
Thanks for your patience Aditya. How does `django-rq` handle asynchronous callbacks in a task in a job queue? 

Are you concerned about `f.result()` blocking indefinitely if `add_done_callback()` isn't used? If that's the case, perhaps you could pass a timeout argument like `f.result(timeout=5) # 5 seconds` and then handle Timeout exception the same way publish failures are handled.
