### ISSUE TITLE
Add documentation for close, and context manager for SubscriberClient

### ISSUE THREAD

**Issue by alonme** [googleapis/python-pubsub#238]
The code examples in `googleapis.dev` do not close the SubscriberClient, and the context manager for this class is not mentioned anywhere, opposed to documenatation in https://cloud.google.com/pubsub/docs/pull .

Not closing the client results in a resource leak, so i think it should be clear from the documentation.

**Comment by meredithslota** [comment]
@alonme Thank you for the report! Can you point me to where in `googleapis.dev` the code samples don't match? I took a quick look and couldn't find it. Generally, the code samples in cloud.google.com will be more thorough.

**Comment by alonme** [comment]
@meredithslota 
The code examples in the following pages, create Subscriber instances, however they don't close them.

https://googleapis.dev/python/pubsub/latest/index.html
https://googleapis.dev/python/pubsub/latest/subscriber/index.html

the code examples in cloud.google.com explicitly state the reason why closing is important and use the context manager, which is totally missing from the `googleapis.dev` docs

**Comment by alonme** [comment]
@meredithslota  @anguillanneuf 

any chance this is also missing from the examples of `PublisherClient` ?

i see that it also has an __exit__ method 

https://github.com/googleapis/python-pubsub/blob/c52aa059cceaea034e902922559ff138df7cd00d/google/pubsub_v1/services/publisher/client.py#L1430

does this also create a resource leak?
