### ISSUE TITLE
samples: add type hints to all samples 

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/python-pubsub#264]
Add type hints so setting "enforce_type_hints" to `True` won't cause lint failures.

https://github.com/googleapis/python-pubsub/blob/258414727827e56d2678ada28b9bbd88b5c6aa6f/samples/snippets/noxfile_config.py#L26-L28

**Comment by plamut** [comment]
@anguillanneuf What's the status of this, have you started working on type hints yet?

If not, I can probably handle this, I'll have some spare cycles.

**Comment by anguillanneuf** [comment]
@plamut Thanks for the ping. If you can handle it, I will review. Thanks again!
