### ISSUE TITLE
pubsub publisher retry settings failing with: TypeError: All attributes being published to Pub/Sub must be sent as text strings. 

### ISSUE THREAD

**Issue by tommyhutcheson** [googleapis/python-pubsub#274]
I have a cloud function which is errors when using the pubsub publisher retry settings on the publisher client or publish requests.
https://cloud.google.com/pubsub/docs/samples/pubsub-publisher-retry-settings#pubsub_publisher_retry_settings-python

When i run my code in JupterLab the python code runs successfully but as soon as I move the code to Cloud Functions I get a TypeError: All attributes being published to Pub/Sub must be sent as text strings. 

I have now tried a new simple Cloud Function copying the code directly from the example in the like above link but still get the same error, any suggestions much appreaciated.

```from google import api_core
from google.cloud import pubsub_v1

# TODO(developer)
GCP_PROJECT_ID='test_project'
SIT_EVENT_TOPIC = ('test_project1')
topic_id=SIT_EVENT_TOPIC
project_id=GCP_PROJECT_ID
# project_id = "your-project-id"
# topic_id = "your-topic-id"

# Configure the retry settings. Defaults shown in comments are values applied
# by the library by default, instead of default values in the Retry object.
def test():
    custom_retry = api_core.retry.Retry(
        initial=0.250,  # seconds (default: 0.1)
        maximum=90.0,  # seconds (default: 60.0)
        multiplier=1.45,  # default: 1.3
        deadline=300.0,  # seconds (default: 60.0)
        predicate=api_core.retry.if_exception_type(
            api_core.exceptions.Aborted,
            api_core.exceptions.DeadlineExceeded,
            api_core.exceptions.InternalServerError,
            api_core.exceptions.ResourceExhausted,
            api_core.exceptions.ServiceUnavailable,
            api_core.exceptions.Unknown,
            api_core.exceptions.Cancelled,
        ),
    )

    publisher = pubsub_v1.PublisherClient()
    topic_path = publisher.topic_path(project_id, topic_id)

    # for n in range(1, 10):
    #     data = "Message number {}".format(n)
    data="test message"
    # Data must be a bytestring
    data = data.encode("utf-8")
    print(type(data))
    future = publisher.publish(topic=topic_path, data=data, retry=custom_retry)
    print(future.result())

    print(f"Published messages with retry settings to {topic_path}.")


def main(event, context):
    """
    Call the main function, sets the order in which to run functions.
    """
    test()

    return 'Script has run without errors !!'

if (__name__ == "__main__"):
    main()
```

output

```ine 40, in test future = publisher.publish(topic=topic_path, data=data, retry=custom_retry) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/google/cloud/pubsub_v1/publisher/client.py", line 195, in publish raise TypeError( TypeError: All attributes being published to Pub/Sub must be sent as text strings.```

**Comment by plamut** [comment]
@tommyhutcheson Thanks for the report.

Unfortunately, I was not able to reproduce the issue neither on my laptop nor when running the code deployed as a Cloud Function, it ran successfully to completion.

![cloud_function](https://user-images.githubusercontent.com/1235663/104731604-3d1e9200-573c-11eb-9349-a9a1afc4b19f.jpg)

Would you mind sharing `requirements.txt` contents used when creating the function? I used the following with Python 3.8:
```txt
# Function dependencies, for example:
# package>=version
google-cloud-pubsub==2.2.0
```

**Comment by tommyhutcheson** [comment]
@plamut thank you for looking into my question, I think you have actually solved it, its a pretty silly error on my part I think.
I had the requirements setup as google-cloud-pubsub==0.34.0 which must have been on another quickstart tutorial, anyway upping the version number has allowed the cloud function to run through, sorry for wasting your time with that one.
Thank you

**Comment by plamut** [comment]
Ah, that makes sense, version `0.34.0` is really dated. I'm glad I was able to help!

**Comment by yasseraj** [comment]
I get the same error when trying to send a PubSub message from container running on K8s (using https://github.com/GoogleCloudPlatform/spark-on-k8s-operator), if I run the same code on my local machine the message is published successfully.
I tested with both version 2.13.12,  2.15.2 and 2.2.0, and nothing, I get the following error.

`Traceback (most recent call last):
  File "/app/sparkjob.py", line 200, in <module>
    pubsub_helper.get_publisher(PUB_ID).publish_event_from_json(event.data, event.get_attributes_map())
  File "/usr/local/lib/python3.7/dist-packages/xriba/pubsub/publisher.py", line 69, in publish_event_from_json
    self.publish_event(json.dumps(json_data), attributes, publish_callback)
  File "/usr/local/lib/python3.7/dist-packages/xriba/pubsub/publisher.py", line 56, in publish_event
    future = self.__pubsub_publisher.publish(self.__topic_path, data=data_to_send, **attributes)
  File "/usr/local/lib/python3.7/dist-packages/google/cloud/pubsub_v1/publisher/client.py", line 359, in publish
    # should be constructed by directly using the raw protobuf class, and only
TypeError: All attributes being published to Pub/Sub must be sent as text strings.`

The content of event.data (dict that is converted into a json string using json.dumps, see the call trace) and event.get_attributes_map() (dict) is the following:
```
print(event.get_attributes_map())
{'event_type': 'IMEX',
 'project_id': 'project-nine',
 'data_version': '1.0.0',
 'meta_data_version': '1.0.0',
 'trace': 'dee5773e-bf74-4c43-93d7-48685r80109d',
 'content_type': 'application/json'}

print(event.data)
{'TEAM': 'DATA_ENGINEERING',
 'bucket': 'gcs_test',
 'table_name': 'clients',
 'export_id': 'e653b134-35f0-43ac-a457-9f400000011'}
print(json.dumps(event.data))
'{"TEAM": "DATA_ENGINEERING", "bucket": "gcs_test", "table_name": "clients", "export_id": "e653b134-35f0-43ac-a457-9f400000011"}'
```
