### ISSUE TITLE
Python Cloud Function cannot get token/identity from metadata server

### ISSUE THREAD

**Issue by donantoniosantos** [googleapis/python-pubsub#285]
Have a python cloud function that is trying to access metadata.google.internal and am getting Internal Server Error 500 when trying to get the token or identity. I get a 200 when I access 'http://metadata/computeMetadata/v1/instance/service-accounts' but anything after default or the service account email addr will give me an error 500. Service account has owner privs in the project.

Code:
```
import requests
from requests.auth import HTTPBasicAuth
import requests
import logging

METADATA_HEADERS = {'Metadata-Flavor': 'Google'}


def hello_world(event,context):
    token_url = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/cloud-platform'
    identity_url = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://oauth2.googleapis.com/token'
    metadata_url = 'http://metadata/computeMetadata/v1/instance/service-accounts/default/token?scope=https://www.googleapis.com/auth/cloud-platform'
    svc_url = 'http://metadata/computeMetadata/v1/instance/service-accounts/default'
    r_token = requests.get(token_url, headers=METADATA_HEADERS)
    r_identity = requests.get(identity_url, headers=METADATA_HEADERS)
    r_metadata = requests.get(metadata_url, headers=METADATA_HEADERS)
    r_svc = requests.get(svc_url, headers=METADATA_HEADERS)

    print(r_token.content)
    print(r_identity.content)
    print(r_metadata.content)
    print(r_svc.content)
```
Output from logs:
```
"b'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/cloud-platform\n'"
"b'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/identity?audience=https://oauth2.googleapis.com/token\n'"
"b'Could not fetch URI /computeMetadata/v1/instance/service-accounts/default/token?scope=https://www.googleapis.com/auth/cloud-platform\n'"
"b'aliases\nemail\nidentity\nscopes\ntoken\n'"
```

**Comment by plamut** [comment]
@donantoniosantos Is this error specifically related to the PubSub library in any way? It appears that we need to move it elsewhere?

With that said, as a sanity check, can you please confirm that all [pre-requisites]((https://cloud.google.com/compute/docs/storing-retrieving-metadata#before-you-begin)) are set up correctly?

500 is kind of unexpected, though, and even if it occurs it should generally be something transient. Is error consistently reproducible?

**Comment by donantoniosantos** [comment]
Hi @plamut, can close this out as I moved this. Only using pubsub as the trigger to the function, ultimately the function would parse the pubsub event, get a token from metadata server, then update a resource based on the context of the pubsub event.. However, this is consistently reproducible for me - 

1. Cloud function - python 3.7 with hello_world as the entry point. Trigger can be any pubsub. Using a service account that has owner privileges.  
2. requirements.txt
```
requests==2.25.1
google-auth==1.18.0
requests-oauthlib==1.3.0
google==3.0.0
```
3. main.py
```
import requests
from requests.auth import HTTPBasicAuth
import requests
import logging

METADATA_HEADERS = {'Metadata-Flavor': 'Google'}


def hello_world(event,context):
    token_url = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token?scopes=https://www.googleapis.com/auth/cloud-platform'
    identity_url = 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=https://oauth2.googleapis.com/token'
    metadata_url = 'http://metadata/computeMetadata/v1/instance/service-accounts/default/token?scope=https://www.googleapis.com/auth/cloud-platform'
    svc_url = 'http://metadata/computeMetadata/v1/instance/service-accounts/default'
    r_token = requests.get(token_url, headers=METADATA_HEADERS)
    r_identity = requests.get(identity_url, headers=METADATA_HEADERS)
    r_metadata = requests.get(metadata_url, headers=METADATA_HEADERS)
    r_svc = requests.get(svc_url, headers=METADATA_HEADERS)

    print(r_token.content)
    print(r_identity.content)
    print(r_metadata.content)
    print(r_svc.content)
```

This should validate, however after testing the function manually, you I get the error messages shown in my post. 

cc: https://github.com/googleapis/gcp-metadata/issues/436

**Comment by plamut** [comment]
@donantoniosantos Thanks for the response, and thanks for opening the other issue in the right place. Closing this then.
