### ISSUE TITLE
PubSub: google.api_core.exceptions.ResourceExhausted: 429 Received message larger than max (28100227 vs. 4194304)

### ISSUE THREAD

**Issue by kpurdon** [googleapis/python-pubsub#3]
It seems this issue has been reported in fixed in a number of other places. I would expect the max size to be 10MB (as documented here: https://cloud.google.com/pubsub/quotas#resource_limits).

Related:

googleapis/google-cloud-python#5574
googleapis/google-cloud-python#5819
googleapis/google-cloud-python#5787

#### Environment details

- MacOS 10.15.2
- Cloud PubSub Emulator via `google/cloud-sdk:272.0.0` docker image

```
google-api-core==1.14.3
google-auth==1.8.2
google-cloud-core==1.1.0
google-cloud-pubsub==1.0.2
google-cloud-storage==1.23.0
google-resumable-media==0.5.0
googleapis-common-protos==1.6.0
grpc-google-iam-v1==0.12.3
```

**Comment by plamut** [comment]
I was able to reproduce this issue in the emulator by posting a message with data of size `4 * 1024 * 1024` (the message overhead nudged the total size over the threshold):

```
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4194364
```

FWIW, after the error the publisher client tried to repeat the 503 error it saw, resulting in a series of errors in the emulator:
```
 io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 5
```
These messages can make the RESOURCE_EXHAUSTED traceback quite easy to overlook, thus mentioning this here if it helps anyone.

@anguillanneuf Do you maybe know whom can we ping to update the threshold in the emulator and release a new version of it? The most recent release seems to bee from September 2019.

Versions used:
```
Google Cloud SDK 282.0.0
beta 2019.05.17
bq 2.0.54
core 2020.02.21
gsutil 4.47
pubsub-emulator 2019.09.27
```

**Comment by anguillanneuf** [comment]
Thanks @plamut, you're right that the last update was from last year. :( 

@kpurdon this issue won't be resolved until a new release is cut. 

@lahuang4 would this be an easy update on the emulator side?

**Comment by plamut** [comment]
Just a status update check - any news to date? Thanks.

**Comment by anguillanneuf** [comment]
Someone is actively working on it, but it isn't a straightforward process, and we're still searching for a fix. Thanks for your patience!

**Comment by anguillanneuf** [comment]
Hi @kpurdon thanks for your patience and checking in. We plan to do this work in Q3. I will update here when a new release of the gcloud SDK picks up the update.

**Comment by kpurdon** [comment]
Hi @anguillanneuf wanted to check in here again - any update? Thanks!

**Comment by anguillanneuf** [comment]
@kpurdon Yes! You shall see the update in the next one or two gcloud releases, sorry we don't have a date yet.
