### ISSUE TITLE
Example of using PublisherClient's `create_topic` method cause TypeError

### ISSUE THREAD

**Issue by OlafMeuwese** [googleapis/python-pubsub#349]
The examples ([here](https://googleapis.dev/python/pubsub/2.4.0/index.html#publishing)) show the `create_topic` like:
```
import os
from google.cloud import pubsub_v1

publisher = pubsub_v1.PublisherClient()
topic_name = 'projects/{project_id}/topics/{topic}'.format(
    project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),
    topic='MY_TOPIC_NAME',  # Set this to something appropriate.
)
publisher.create_topic(topic_name) # this is the problem
```

However, if you run this, you get

#### Stack trace
```
/lib/python3.8/site-packages/proto/message.py in __init__(self, mapping, ignore_unknown_fields, **kwargs)
    484         else:
    485             # Sanity check: Did we get something not a map? Error if so.
--> 486             raise TypeError(
    487                 "Invalid constructor input for %s: %r"
    488                 % (self.__class__.__name__, mapping,)

TypeError: Invalid constructor input for Topic: 'projects/<project_id>/topics/MY_TOPIC_NAME'
```

#### Possible solution

```
import os
from google.cloud import pubsub_v1

publisher = pubsub_v1.PublisherClient()
topic_name = 'projects/{project_id}/topics/{topic}'.format(
    project_id=os.getenv('GOOGLE_CLOUD_PROJECT'),
    topic='MY_TOPIC_NAME',  # Set this to something appropriate.
)
publisher.create_topic({"name": topic_name})
```

or 
```
publisher.create_topic(name=topic_name)
```

#### Environment details

  - OS type and version: `MacOs Big Sur (11.2.3)`
  - Python version: `3.8.5`
  - pip version: `21.0.1` 
  - `google-cloud-pubsub` version: `2.3.0`

**Comment by plamut** [comment]
@OlafMeuwese Thanks for the report, I can reproduce the behavior.

The thing is that [create_topic()](https://github.com/googleapis/python-pubsub/blob/15e0f648bdd0e4ea7cf555416def2e6744761148/google/pubsub_v1/services/publisher/client.py#L398-L406) expects a `request` object as its positional argument, or a topic name passed as a string via the `name` keyword-only argument.

The code sample in question is incorrect, thanks for catching that!
