### ISSUE TITLE
pubsub: expose a max_duration_per_lease_extension setting for subscribers

### ISSUE THREAD

**Issue by hongalex** [googleapis/python-pubsub#35]
For languages that support lease management, we have bound the percentile distribution to 10s - 10m. It would be useful if the upper bound were configurable.

A user might process messages very slowly (8m to ack)
If the application fails 5s after receiving a message (whose ack deadline was set to 8m, because that's the deadline the percentile distribution gave), the user has to wait 7m55s for the message to be redelivered
Users should be able to set `max_duration_per_lease_extension` = 20s, which caps an individual modAck RPC to 20s. This would have the downside of causing more modack RPCs to be sent, but the upside that the redelivery time would only be 15s
This setting differs from [`max_lease_duration`](https://github.com/googleapis/google-cloud-dotnet/blob/174e30c1ef39c5d1e1e51590b6af402aa0316c54/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1/SubscriberClient.cs#L229), which defines the total amount of time we'll hold a message.

In addition, `max_duration_per_lease_extension` should be disabled if <=0, and should default to 0.

**Comment by IlyaFaer** [comment]
@pradn, that was me, who did this for Go, and, if you don't mind, I'll do this for Python as well

**Comment by pradn** [comment]
@IlyaFaer Sounds good, Ilya. Reach out if you have any questions.

**Comment by IlyaFaer** [comment]
@pradn, yes, I'm taking a look at `ack_deadline()` property and I don't see where `_last_histogram_size` value is changed. I found only two places, where it's used:
https://github.com/googleapis/python-pubsub/blob/380cb384217a0a032ded3d7586804c2373af5015/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L111
and
https://github.com/googleapis/python-pubsub/blob/380cb384217a0a032ded3d7586804c2373af5015/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py#L194
Am I missing something, or `target` in here will always be equal to 100? Looks like something that needs to be fixed

**Comment by hongalex** [comment]
Hey @IlyaFaer, we finalized the naming for all languages and updated the original issue. Please update when you get the chance.

**Comment by IlyaFaer** [comment]
@hongalex, @pradn, okay, it's done
