### ISSUE TITLE
The version of the library is currently 2.4.0 but the documentation says that it is 1.y.z and all the code examples uses xxxxx_v1

### ISSUE THREAD

**Issue by lopezvit** [googleapis/python-pubsub#351]
I don't understand why the documentation says that the version of the library is 1.y.z when it is already in version 2.4.0.
Also, why are all the examples of the library (https://cloud.google.com/pubsub/docs/publisher#python_1 https://googleapis.dev/python/pubsub/latest/publisher/api/client.html) using *_v1?
e.g.
`from google.cloud import pubsub_v1`
instead of 
`from google.cloud import pubsub` ?

**Comment by plamut** [comment]
@lopezvit That "v1" refers to the version of the backend API the client library implements, while the library version itself is indeed `2.x` at the time of writing.

The `google.cloud.pubsub package` is just a veneer over `google.cloud.pubsub_v1` (check [`__init__.py`](https://github.com/googleapis/python-pubsub/blob/master/google/cloud/pubsub/__init__.py)). Not sure why some of the samples use `pubsub_v1` directly, though, do you maybe know @anguillanneuf ?

**Comment by plamut** [comment]
@lopezvit Did this answer all the questions you had? Could the ticket be closed or is there something else we could help with?

**Comment by lopezvit** [comment]
No, It has responde my question, thank you.
