### ISSUE TITLE
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

### ISSUE THREAD

**Issue by kthulsidoss** [googleapis/python-pubsub#36]
Hi We are using google pub sub api for implementing the publisher /subscribe pattern and we have synchronous pull implemented (ref :synchronous_pull (project_id, subscription_name).
I find from viewing the topic that message has been reached the topic however it does not reach the subscriber with the above exception (google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded).
Here are the details
OS :Red Hat 4.8.5-39
Python : 2.7.5
Would deeply appreciate your response

**Comment by kthulsidoss** [comment]
Internal Server Error: /api/MDRTestSubscriberCall/9/
Traceback (most recent call last):
  File "/opt/secadm/xyzadm/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/secadm/xyzadm/env/lib/python3.6/site-packages/grpc/_channel.py", line 824, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/secadm/xyzadm/env/lib/python3.6/site-packages/grpc/_channel.py", line 726, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "Deadline Exceeded"
        debug_error_string = "{"created":"@1582534133.959908992","description":"Error received from peer ipv4:172.217.166.42:443","file":"src/core/lib/surface/call.cc","file_l
ine":1056,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
The above exception was the direct cause of the following exception:
File "<string>", line 3, in raise_from
google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded

**Comment by plamut** [comment]
This looks very similar to #7, and especially #9. It is reported that this has to do with the `initial_rpc_timeout_millis` setting. It will be set back to 25000 shortly (as per [comment](https://github.com/googleapis/python-pubsub/issues/9#issuecomment-590650571)).

One maybe-workaround could also be passing the `return_immediately=True` argument, although that might not work in all cases, and the parameter itself is actually deprecated - but it might be a "good enough" fix in the short term.

By the way, generally the [asynchronous (streaming) pull](https://cloud.google.com/pubsub/docs/pull#asynchronous-pull) is the preferred method of pulling messages. If it's feasible with your use case, you might also want to use that instead of the synchronous pull.

**Comment by kamalaboulhosn** [comment]
I would recommend against setting `return_immediately=True`. This parameter is deprecated and will also have implications for your ability to receive messages quickly.

**Comment by kthulsidoss** [comment]
I dont see (need to recheck on the deadline error code) however i see the messages sitting in the topic/subscription. Before this flag i used to get the deadline error , but the message getting processed. So does that mean the message is recieved by the subscriber and all the actions are not completed.
Tx
k.thulsi doss

**Comment by kthulsidoss** [comment]
Dear Support ,i'm getting the following error in python
message is undefined ,could you please provide appropriate imports for this type.
tx
k.thulsi doss

**Comment by plamut** [comment]
@kthulsidoss Would it be possible to provide a minimal reproducible code sample? Is the "message undefined" a `NameError`? The latter sounds more like a bug outside of the client library.

Also, there are working [code samples](https://cloud.google.com/pubsub/docs/pull#synchronous_pull) listed in the PubSub documentation, if it helps.

**Comment by kthulsidoss** [comment]
# TODO project_id = "Your Google Cloud Project ID"
# TODO subscription_name = "Your Pub/Sub subscription name"
# TODO timeout = 5.0  # "How long the subscriber should listen for
# messages in seconds"

subscriber = pubsub_v1.SubscriberClient()
# The `subscription_path` method creates a fully qualified identifier
# in the form `projects/{project_id}/subscriptions/{subscription_name}`
subscription_path = subscriber.subscription_path(
    project_id, subscription_name
)

def callback(message):
    print("Received message: {}".format(message))
    data = message.decode('utf-8')
    format = "%Y-%m-%d %H:%M:%S %Z%z"
    now_utc = datetime.now(timezone('UTC'))
    # data=received_message.message.data
    data = json.loads(data)
    print("TDK printing before the steps that needs to be done after the data -->>>> ",now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
    print("TDK printing the recieved data >>>>>>******************",now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data)
    # attributes = message.attributes
    # first array element is request_id = data.split(":")[0]
    # second array element is json = data.split(":")[1] then construct json object json.loads(data.split(":")[1])
    # request_id = data.split(":")[1]
    print("TDK printing the request_type from synchronous pull method*****************->", now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format),data['request_type'])
    print("TDK printing the request_id from synchronous pull *****************->", now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format),data['request_id'])
    print("TDK printing the gsr_id from synchronous pull *****************->", data['gsr_id'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
    print("TDK printing the Security-Sync_State from synchronous pull method*****************---->", now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format),data['Security_Sync_State'])
    print("TDK printing the s_json from synchronous pull method *****************->", data['s_json'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
    ss = SecAdmSecurityService(data['s_json'], data['request_id'])
    st_json_name = ss.process_the_security_json()
    print("!!!!!!!!!!st_json_name!!!!!!!!!!!!", st_json_name)
        try:
            print("&&&&&&&&&sts&&&&&")
            
           
            print("&&&&&&&&&stswhile reading json&&&&&", sts, sts_ms)
        except KeyError as e:
            print("@@@@@@@@@Exception@@@@@@@", e)
           
            print("****************INSIDE EXCEPTION*********")
          
         else:
            
            
            print("Received: {}".format(received_message.message.data))
        #ack_ids.append(received_message.ack_id)
    message.ack()

streaming_pull_future = subscriber.subscribe(
    subscription_path, callback=callback
)
print("Listening for messages on {}..\n".format(subscription_path))

# result() in a future will block indefinitely if `timeout` is not set,
# unless an exception is encountered first.
try:
    streaming_pull_future.result(timeout=timeout)
except:  # noqa
    streaming_pull_future.cancel()

**Comment by kthulsidoss** [comment]
Let me recheck -it could be indendation issue

**Comment by plamut** [comment]
Just a readabilty tip - putting the code block inside the code block delimiters will render it more nicely:

\`\`\`py
python code here
\`\`\`

I edited your comment for better readability.

**Comment by kthulsidoss** [comment]
hi @plamut i dont see the actions under callback being done ? i dont see the print statements in the log . Can you please kindly reopen ?

**Comment by plamut** [comment]
@kthulsidoss Could you please re-post the code sample first? I saw it briefly, and it appears that the _asynchronous_ pull was used there? Thanks!

**Comment by kthulsidoss** [comment]
def synchronous_pull_apply_security_targetapplications(project_id, subscription_name):
    from google.cloud import pubsub_v1

    
    subscriber = pubsub_v1.SubscriberClient()
   
    subscription_path = subscriber.subscription_path(
        project_id, subscription_name)

    def callback(message):
        print("Received message: {}".format(message))
        data = message.decode('utf-8')
        format = "%Y-%m-%d %H:%M:%S %Z%z"
        now_utc = datetime.now(timezone('UTC'))
       
        data = json.loads(data)
        print("TDK printing before the steps that needs to be done after the data -->>>> ",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        print("TDK printing the recieved data >>>>>>******************",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data)
        
        print("TDK printing the request_type from synchronous pull method*****************->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['request_type'])
        print("TDK printing the request_id from synchronous pull *****************->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['request_id'])
        print("TDK printing the gsr_id from synchronous pull *****************->",
              data['gsr_id'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        print("TDK printing the Security-Sync_State from synchronous pull method*****************---->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['Security_Sync_State'])
        print("TDK printing the s_json from synchronous pull method *****************->",
              data['s_json'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        ss = SecAdmSecurityService(data['s_json'], data['request_id'])
        st_json_name = ss.process_the_security_json()
        print("!!!!!!!!!!st_json_name!!!!!!!!!!!!", st_json_name)
        try:
            print("&&&&&&&&&sts&&&&&")
            msas = MasterSecadmService(
                data['request_type'], data['request_id'], data['gsr_id'], data['Security_Sync_State'])
            sts, sts_ms = msas.read_status_json(st_json_name)
            print("&&&&&&&&&stswhile reading json&&&&&", sts, sts_ms)
        except KeyError as e:
            print("@@@@@@@@@Exception@@@@@@@", e)
            s_r = security_requests.objects.filter(
                request_id=data['request_id'])
            print("****************INSIDE EXCEPTION*********")
            s_r.update(status='-1: Error', status_message=str(e))
        else:
            s_r = security_requests.objects.filter(request_id=self.request_id)
            s_r.update(status=sts if sts == 'SUCCESS' else sts,
                       status_message=sts_ms)
        print("Received: {}".format(received_message.message.data))
        
        message.ack()

    streaming_pull_future = subscriber.subscribe(
        subscription_path, callback=callback)
    print("Listening for messages on {}..\n".format(subscription_path))

   
    try:
        streaming_pull_future.result(timeout=timeout)
    except:  # noqa
        streaming_pull_future.cancel()

**Comment by plamut** [comment]
@kthulsidoss Let's move the discussion under the [new issue](https://github.com/googleapis/python-pubsub/issues/39) (I copied the code snippet there), as this code uses the asynchronous (streaming) pull.

**Comment by kthulsidoss** [comment]
@plamut also i see that the message has been published and it is in the Topic this means that it was not processed by the subscriber. Although i see a line in the log 'Listening for messages on projects/atomic-monument-267912/subscriptions/security_receive..' and this line is after the message.ack().
