### ISSUE TITLE
RunTime error occurs when shutting down the streaming pull manager on user callback exception

### ISSUE THREAD

**Issue by kthulsidoss** [googleapis/python-pubsub#39]
@plamut i no longer receive the deadline exceeded error #36  however i dont see the actions being perfomed under 
def callback(message)
Can you please help on this

**Comment by plamut** [comment]
@kthulsidoss Please provide a code sample so that we can take a look, thanks!

**Comment by plamut** [comment]
From the [comment](https://github.com/googleapis/python-pubsub/issues/36#issuecomment-591980759) on another issue:

```py
def synchronous_pull_apply_security_targetapplications(project_id, subscription_name):
    from google.cloud import pubsub_v1

    
    subscriber = pubsub_v1.SubscriberClient()
   
    subscription_path = subscriber.subscription_path(
        project_id, subscription_name)

    def callback(message):
        print("Received message: {}".format(message))
        data = message.decode('utf-8')
        format = "%Y-%m-%d %H:%M:%S %Z%z"
        now_utc = datetime.now(timezone('UTC'))
       
        data = json.loads(data)
        print("TDK printing before the steps that needs to be done after the data -->>>> ",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        print("TDK printing the recieved data >>>>>>******************",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data)
        
        print("TDK printing the request_type from synchronous pull method*****************->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['request_type'])
        print("TDK printing the request_id from synchronous pull *****************->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['request_id'])
        print("TDK printing the gsr_id from synchronous pull *****************->",
              data['gsr_id'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        print("TDK printing the Security-Sync_State from synchronous pull method*****************---->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['Security_Sync_State'])
        print("TDK printing the s_json from synchronous pull method *****************->",
              data['s_json'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        ss = SecAdmSecurityService(data['s_json'], data['request_id'])
        st_json_name = ss.process_the_security_json()
        print("!!!!!!!!!!st_json_name!!!!!!!!!!!!", st_json_name)
        try:
            print("&&&&&&&&&sts&&&&&")
            msas = MasterSecadmService(
                data['request_type'], data['request_id'], data['gsr_id'], data['Security_Sync_State'])
            sts, sts_ms = msas.read_status_json(st_json_name)
            print("&&&&&&&&&stswhile reading json&&&&&", sts, sts_ms)
        except KeyError as e:
            print("@@@@@@@@@Exception@@@@@@@", e)
            s_r = security_requests.objects.filter(
                request_id=data['request_id'])
            print("****************INSIDE EXCEPTION*********")
            s_r.update(status='-1: Error', status_message=str(e))
        else:
            s_r = security_requests.objects.filter(request_id=self.request_id)
            s_r.update(status=sts if sts == 'SUCCESS' else sts,
                       status_message=sts_ms)
        print("Received: {}".format(received_message.message.data))
        
        message.ack()

    streaming_pull_future = subscriber.subscribe(
        subscription_path, callback=callback)
    print("Listening for messages on {}..\n".format(subscription_path))

   
    try:
        streaming_pull_future.result(timeout=timeout)
    except:  # noqa
        streaming_pull_future.cancel()
```

**Comment by kthulsidoss** [comment]
@plamut are you needing to see anything from the log ?

**Comment by plamut** [comment]
From the [comment](https://github.com/googleapis/python-pubsub/issues/36#issuecomment-591983215):

> also i see that the message has been published and it is in the Topic this means that it was not processed by the subscriber. Although i see a line in the log 'Listening for messages on projects/atomic-monument-267912/subscriptions/security_receive..' and this line is after the message.ack().

It seems that `timeout` is not defined and the script exits. Could you try setting it?

**Comment by kthulsidoss** [comment]
now the result of the api call (async call) is set_result can only be called once.

**Comment by kthulsidoss** [comment]
now the result of the api call (async call) is set_result can only be called once.

**Comment by kthulsidoss** [comment]
here is further problematic ones
Received message: Message {
  data: b'{"request_type": "Apply_security_to_target_applica...'
  attributes: {}
}
Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
  File "/opt/secadm/hsbcsecadm/env/lib/python3.6/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 77, in _wrap_callback_errors
    callback(message)
  File "./api/views.py", line 322, in callback
    data = message.decode('utf-8')

**Comment by plamut** [comment]
@kthulsidoss I was able to reproduce it, and the following appears in the log output:

```
    ...
    data = message.decode('utf-8')
AttributeError: 'Message' object has no attribute 'decode'
```

Messages received with the streaming pull are wrapped into a [Message](https://googleapis.dev/python/pubsub/latest/subscriber/api/message.html#google.cloud.pubsub_v1.subscriber.message.Message) class, thus the following:

```py
data = message.decode('utf-8')
```

needs to be changed to:

```py
data = message.data.decode('utf-8')
```

**Comment by plamut** [comment]
I changed the issue title to reflect the issue on shutdown that was revealed here (the original issue was caused due to the bug in the provided callback).

**Comment by plamut** [comment]
I changed the issue title to reflect the issue on shutdown that was revealed here (the original issue was caused due to the bug in the provided callback).

**Comment by kthulsidoss** [comment]
I see the actions being performed under callback,how ever i get a 502 response from the api (bad gateway)

**Comment by kthulsidoss** [comment]
I can see that the message is sitting at the topic (is this ok, based on my previous experience i find that it should get processed and not remain in topic

**Comment by kthulsidoss** [comment]
Hi @plamut can you please let us know when we can get this fix/workaround to use . 
Appreciate your help.
Tx
k.thulsi doss

**Comment by plamut** [comment]
@kthulsidoss Which one are you referring to? (there have been multiple questions in the discussion)

If asking about the observed RuntimeError, I will probably take a look at it in the next few days, although that seems to only happen if the provided callback raises an exception (please double check that the callback is now bug-free).

However, If asking about the messages "still sitting in the topic", or about the 502 error with the streaming (async) pull, some more details will be needed - ideally a code sample that can consistently reproduce the reported behavior (I haven't observed any that yesterday during the quick tests).

**Comment by kthulsidoss** [comment]
@plamut  i'm asking about the 502 error , is there a email id which i could send over to you officially with this git issue id . That way we all can be assured of the help,support w.r.t to passing info to management.
Thanks a lot
K.thulsi doss

**Comment by plamut** [comment]
@kthulsidoss I'm an external maintainer, thus I cannot say for certain, but I will ask and let you know as soon as I get an answer.

**Comment by kamalaboulhosn** [comment]
@kthulsidoss For the 502 issue, this is likely a problem with either a firewall or network configuration if they happen consistently. A generic code sample can be posted here if it can reproduce the issue. If the example requires code that has private code or you need support for a particular project ID, then you'd need to contact [Google Cloud Support](https://console.cloud.google.com/support) and reference this GitHub issue.

**Comment by kthulsidoss** [comment]
def synchronous_pull_apply_security_targetapplications(project_id, subscription_name):
    from google.cloud import pubsub_v1

       subscriber = pubsub_v1.SubscriberClient()
    
    subscription_path = subscriber.subscription_path(
        project_id, subscription_name)

    def callback(message):
        print("Received message: {}".format(message))
        #data = message.decode('utf-8')
        data = message.data.decode('utf-8')
        format = "%Y-%m-%d %H:%M:%S %Z%z"
        now_utc = datetime.now(timezone('UTC'))
       
        data = json.loads(data)
        print("TDK printing before the steps that needs to be done after the data -->>>> ",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        print("TDK printing the recieved data >>>>>>******************",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data)
        
        print("TDK printing the request_type from synchronous pull method*****************->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['request_type'])
        print("TDK printing the request_id from synchronous pull *****************->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['request_id'])
        print("TDK printing the gsr_id from synchronous pull *****************->",
              data['gsr_id'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        print("TDK printing the Security-Sync_State from synchronous pull method*****************---->",
              now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format), data['Security_Sync_State'])
        print("TDK printing the s_json from synchronous pull method *****************->",
              data['s_json'], now_utc.astimezone(timezone('Asia/Kolkata')).strftime(format))
        ss = SecAdmSecurityService(data['s_json'], data['request_id'])
        st_json_name = ss.process_the_security_json()
        print("!!!!!!!!!!st_json_name!!!!!!!!!!!!", st_json_name)
        try:
            print("&&&&&&&&&sts&&&&&")
            msas = MasterSecadmService(
                data['request_type'], data['request_id'], data['gsr_id'], data['Security_Sync_State'])
            sts, sts_ms = msas.read_status_json(st_json_name)
            print("&&&&&&&&&stswhile reading json&&&&&", sts, sts_ms)
        except KeyError as e:
            print("@@@@@@@@@Exception@@@@@@@", e)
            s_r = security_requests.objects.filter(
                request_id=data['request_id'])
            print("****************INSIDE EXCEPTION*********")
            s_r.update(status='-1: Error', status_message=str(e))
        else:
            s_r = security_requests.objects.filter(request_id=self.request_id)
            s_r.update(status=sts if sts == 'SUCCESS' else sts,
                       status_message=sts_ms)
        print("Received: {}".format(received_message.message.data))
      
        message.ack()

    streaming_pull_future = subscriber.subscribe(
        subscription_path, callback=callback)
    print("Listening for messages on {}..\n".format(subscription_path))

  
    try:
        streaming_pull_future.result(timeout=300)
    except:  # noqa
        streaming_pull_future.cancel()
