### ISSUE TITLE
Support authentication using end user credentials from Google Cloud SDK

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/python-pubsub#402]
Crossed filed in Java: https://github.com/googleapis/java-pubsub/issues/636

If `GOOGLE_APPLICATION_CREDENTIALS` is unset but the end user - who has the necessary IAM roles and permissions - is signed in with gcloud SDK (check the account field in `gcloud config list`), the calls made to Pub/Sub should still succeed.

The Java library throws a nice warming that the Python library doesn't: `WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.`

Stacktrace says `Bad Request` and points me to the `plugin_credentials.cc` file. It should have a way to use gcloud end user credentials.
```sh
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 73, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/tianzi/py39/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/tianzi/py39/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')"
	debug_error_string = "{"created":"@1619720380.424752000","description":"Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')","file":"src/core/lib/security/credentials/plugin/plugin_credentials.cc","file_line":93,"grpc_status":14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tianzi/VSCodeProjects/python-pubsub/samples/snippets/publisher.py", line 426, in <module>
    list_topics(args.project_id)
  File "/Users/tianzi/VSCodeProjects/python-pubsub/samples/snippets/publisher.py", line 38, in list_topics
    for topic in publisher.list_topics(request={"project": project_path}):
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/pubsub_v1/services/publisher/client.py", line 756, in list_topics
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "/Users/tianzi/py39/lib/python3.9/site-packages/google/api_core/retry.py", line 199, in retry_target
    six.raise_from(
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x110410310>, project: "projects/tz-playground-bigdata"
, metadata=[('x-goog-request-params', 'project=projects/tz-playground-bigdata'), ('x-goog-api-client', 'gl-python/3.9.4 grpc/1.37.0 gax/1.26.3 gccl/2.4.1')]), last exception: 503 Getting metadata from plugin failed with error: ('invalid_grant: Bad Request', '{\n  "error": "invalid_grant",\n  "error_description": "Bad Request"\n}')
```

**Comment by plamut** [comment]
@anguillanneuf Can you please elaborate what needs to be done here? After some investigation it appears that this feature is already working with the Python client?

Test script:
```
$ cat test.py 
from google.cloud.pubsub import PublisherClient

print("Creating publisher instance...")
client = PublisherClient()
print("Publisher instance created successfully.")
```

Before authenticating with Google Cloud SDK:

```
$ unset GOOGLE_APPLICATION_CREDENTIALS
$ python test.py
Creating publisher instance...
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    client = PublisherClient()
    ...
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

After authenticating:

```
$ gcloud auth application-default login
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?...

Credentials saved to file: [<home>/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
...

$ python test.py
Creating publisher instance...
Publisher instance created successfully.
```

Is this what the feature request is about?

**Comment by anguillanneuf** [comment]
Thank you @plamut.

I see the difference. You are probably right about `gcloud auth application-default login` being the right approach for application credentials, not `gcloud auth login` for end user credentials. @busunkim96 Can I confirm with you?

**Comment by anguillanneuf** [comment]
Hmm, the Java client is able to find the end user credentials if I log in with `gcloud auth login`. This worked for me:

```sh
git clone https://github.com/googleapis/java-pubsub.git
cd java-pubsub/samples/snippets
# update `projectId` to my project ID in `src/main/java/pubsub/ListSchemasExample.java`
unset GOOGLE_APPLICATION_CREDENTIALS
gcloud auth login
mvn compile exec:java -Dexec.mainClass=pubsub.ListSchemasExample
```

**Comment by busunkim96** [comment]
@anguillanneuf My understanding is that `gcloud auth login` (end user credentials) should _also_ work at this point. (see flowchart on [this page](https://cloud.google.com/docs/authentication/best-practices-applications)).

This _seems_ to work for me although I do get the warning about end user credentials. 

```
(env) busunkim-macbookpro1% python3 test_pubsub.py 
/Users/busunkim/env/lib/python3.6/site-packages/google/auth/_default.py:70: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
<class 'google.oauth2.credentials.Credentials'>
Creating publisher instance...
Publisher instance created successfully.
```

```py
(env) busunkim-macbookpro1% cat test_pubsub.py 
from google.cloud.pubsub import PublisherClient

import google.auth

creds, project_id = google.auth.default()
print(type(creds))

print("Creating publisher instance...")
client = PublisherClient(credentials=creds)
print("Publisher instance created successfully.")

```

Right now you will always see the warning ([google-auth code](https://github.com/googleapis/google-auth-library-python/blob/09e0389db72cc9d6c5dde34864cb54d717dc0b92/google/auth/_default.py#L124-L139)) - I think that can be fixed with some small changes.

@arithmetic1728 Is the auth library supposed to figure out the quota project from the environment and apply it for ADC?

**Comment by anguillanneuf** [comment]
Thank you @busunkim96 ! I see in your code you call `google.auth.default()` explicitly, which I wasn't doing when testing `gcloud auth login`. I hope that's still expected? 

From what I understand, `google.auth.default()` looks for a `~/.config/gcloud/application_default_credentials.json` file created by `gcloud auth applications-default login`. But `gcloud auth login` creates a `~/.config/gcloud/credentials.db` and a `~/.config/gcloud/legacy_credentials/$USER_EMAIL/adc.json`. I did not check if `credentials.db` and `adc.json` are used by the Google Auth library.

**Comment by arithmetic1728** [comment]
@busunkim96 @anguillanneuf 
Yes, ADC relies on `~/.config/gcloud/application_default_credentials.json` file, and it is only created by `gcloud auth application-default login`. So `gcloud auth login` won't work.

**Comment by plamut** [comment]
Thanks all for having a closer look.

So to summarize - assuming that `GOOGLE_APPLICATION_CREDENTIALS` is **not** set¸ creating a client instance with no explicit credentials **should not** work, even if calling `gcloud auth login` beforehand? It should work only if `gcloud auth application-default login` is used?

In other words, the [current behavior](https://github.com/googleapis/python-pubsub/issues/402#issuecomment-853811721) is in line with expectations and this issue can remain closed?

**Comment by arithmetic1728** [comment]
@plamut If a client instance is created with no explicit credential, then it looks for the application default credential in the following order:
(1) the file `GOOGLE_APPLICATION_CREDENTIALS` points to
(2) the file created by `gcloud auth application-default login`
(3) if the client is running on VM environment like compute engine, then credential can be obtained from the metadata server on the VM

Therefore, if none of these exists, then there is no credential. 
`gcloud auth login` is for gcloud CLI to use only, it is not intended for client and auth libraries to use. 
The current behavior is the right behavior.

**Comment by plamut** [comment]
@arithmetic1728 Thanks for confirming, and explaining the default credentials flow!
