### ISSUE TITLE
ListTopicsPager is not linked in API reference docs

### ISSUE THREAD

**Issue by tswast** [googleapis/python-pubsub#436]
https://googleapis.dev/python/pubsub/latest/publisher/api/client.html#google.cloud.pubsub_v1.publisher.client.Client.list_topics

I'd expect the ListTopicsPager reference to link to more documentation. Currently it's just the class name and I have to code search to find out how to use it.

**Comment by plamut** [comment]
@tswast This is in the autogenerated code, perhaps the request should be moved to the generator repo? If possible, I'd fix is there instead of patching the generated code with synth/owlbot.

**Comment by tswast** [comment]
I think adding a `pagers.rst` file similar to https://github.com/googleapis/python-pubsub/blob/master/docs/publisher/api/client.rst should fix it.

**Comment by plamut** [comment]
Tried it, it worked. Will submit a PR shortly.
