### ISSUE TITLE
Error 500 when creating Subscriber in Pub/Sub with OIDCToken object in Python

### ISSUE THREAD

**Issue by akouminov** [googleapis/python-pubsub#480]
Problem you have encountered:

I received this error when trying to create a Pub/Sub subscription through the Python library

> <_InactiveRpcError of RPC that terminated with:
> 	status = StatusCode.INTERNAL
> 	details = "A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]"
> 	debug_error_string = "{"created":"@1626033094.473000000","description":"Error received from peer [REDACTED]","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]","grpc_status":13}"
> >

What you expected to happen: A Pub/Sub subscription to be created under specified topic

Steps to reproduce:

Here is the snippet of code I am using

```
from google.cloud import pubsub_v1
from google.api_core.exceptions import NotFound, InternalServerError
from google.cloud.pubsub_v1.types import PushConfig
import time

<inputs are geo, function_handler, project_id>
    
if not publisher:
        publisher = pubsub_v1.PublisherClient(
            publisher_options = pubsub_v1.types.PublisherOptions(enable_message_ordering=True)
        )
    topic_path = publisher.topic_path(project_id, "dynamo_%s" % str(geo))
    print("checking if the topic already exists")
    try:
        topic = publisher.get_topic(topic=topic_path)
        print("Topic already exists: {}".format(topic.name))
    except NotFound:
        print("Topic does not exist, creating...")
        topic = publisher.create_topic(request={"name": topic_path})
        print("Created topic: {}".format(topic.name))
        print("Creating Push Subscription...")
        push_config = PushConfig(push_endpoint=function_handler,
         oidc_token=PushConfig.OidcToken(service_account_email='[REDACTED]'))
        
        subscriber_client = pubsub_v1.SubscriberClient()
        for _ in range(2):
            try:
                time.sleep(1)
                subscription_path = subscriber_client.subscription_path(project_id, "dynamo_%s_sub" % str(geo))
                sub_resp = subscriber_client.create_subscription(name=subscription_path,
                topic=topic_path, push_config=push_config, ack_deadline_seconds=600)
                break
            except InternalServerError as exp:
                print("topic not ready yet, waiting 5 seconds and retrying")
                time.sleep(5)
                print("5 seconds is up, retrying!")
                if _ < 1:
                    continue
                else:
                    raise exp
        print("Created Push Subscription")
        print(sub_resp)
```
Other information (workarounds you have tried, documentation consulted, etc):

This code worked when I omit the OIDCToken object, but I require for the service account to be attached to the subscription for push calls from my subscriber to cloud functions.

I have consulted these docs: https://googleapis.dev/python/pubsub/latest/types.html

And repo: https://github.com/googleapis/python-pubsub/blob/c1f0350f8fa2070cf831f0934991fed1b02ff646/google/pubsub_v1/types/pubsub.py

I opened a case with https://issuetracker.google.com/issues/195645104
this was determined to be an issue in the library and I was referred here after testing that the API is working correctly: Copying the comment here:

after investigating we found that the API is working properly. As a workaround you could use the command [0] to create the subscription in your desire way, with that, I manged to get 200 responses. The issue seems to be in the python library.

We understand that this may dont fulfill all of the requirements. In order to further proceed, according to [1], we should contact the team in charge of the library through git hub issues tracker [2], please explain there why we discard that the API is not the one that is provoking the issue.

This thread will be mark as close since is not possible to proceed from this perspective.

[0] -

```
curl --request PUT
'https://pubsub.googleapis.com/v1/projects/[PROJECT_ID]/subscriptions/[SUBSCRIPTION_NAME]?key=[YOUR_API_KEY]'
--header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]'
--header 'Accept: application/json'
--header 'Content-Type: application/json'
--data '{"pushConfig":{"pushEndpoint":"https://example.com/push","oidcToken":{"serviceAccountEmail":"[SERVICE_ACCOUNT]"}},"topic":"projects/[PROJECT_ID]/topics/[TOPIC}"}'
--compressed
```

**Comment by meredithslota** [comment]
@hannahrogers-google Can you help route this to the right person to investigate this?

**Comment by plamut** [comment]
@akouminov Thanks for the detailed report and the research you did on your own.

Just to verify, is this issue consistently reproducible whenever you want to create a new subscription with `PushConfig`? Or is it something that you observed on a few occasions, but otherwise works in normal circumstances?
(in which case the library might want to automatically repeat a request on similar error responses)

**Comment by a-koumi** [comment]
This happens every time in my environment, this was also confirmed in the case that I opened, it works if I do not attach an OIDC token, but it fails when I attach the OIDC token with the service account as I need the push that happens to be authenticated for the push in pub/sub

**Comment by akouminov** [comment]
This happens every time in my environment, this was also confirmed in the case that I opened, it works if I do not attach an OIDC token, but it fails when I attach the OIDC token with the service account as I need the push that happens to be authenticated for the push in pub/sub

**Comment by akouminov** [comment]
if you could, cloud you post the code you have that is working?

**Comment by plamut** [comment]
> if you could, cloud you post the code you have that is working?

Sure thing. It's essentially just a simplified version of your script:
```py
from google.cloud import pubsub_v1
from google.api_core.exceptions import NotFound
from google.cloud.pubsub_v1.types import PushConfig


PROJECT_ID = "my_project"
TOPIC_ID = "my_topic"
SUBSCRIPTION_ID = "my_subscription"
    

publisher = pubsub_v1.PublisherClient(
    publisher_options = pubsub_v1.types.PublisherOptions(enable_message_ordering=True)
)
topic_path = publisher.topic_path(PROJECT_ID, TOPIC_ID)

try:
    topic = publisher.get_topic(topic=topic_path)
    print("Topic already exists: {}".format(topic.name))
except NotFound:
    print("Topic does not exist, creating...")
    topic = publisher.create_topic(request={"name": topic_path})
    print("Created topic: {}".format(topic.name))

print("Creating Push Subscription...")
push_config = PushConfig(
    push_endpoint="https://example.com/push",
    oidc_token=PushConfig.OidcToken(
        service_account_email="my-service-account@email.foo"
    )
)

subscriber_client = pubsub_v1.SubscriberClient()
subscription_path = subscriber_client.subscription_path(PROJECT_ID, SUBSCRIPTION_ID)

sub_resp = subscriber_client.create_subscription(
    name=subscription_path,
    topic=topic_path,
    push_config=push_config,
    ack_deadline_seconds=600,
)

print("Created Push Subscription")
print(sub_resp)
```

Is there anything in this simplified version that significantly differs from your actual code?

FWIW, I tested this with Python 3.8 and `google-cloud-pubsub==2.7.1` and `grpcio==1.39.0` on Ubuntu Linux. Which versions did you use?

**Comment by akouminov** [comment]
Thank you so much for getting back to me, I will gather some information about my environment and get back to you

**Comment by akouminov** [comment]
I got it working with python 3.8!

**Comment by akouminov** [comment]
working with python7 as well, thank you!

**Comment by plamut** [comment]
@akouminov I'm glad that you got it working at the end!
