### ISSUE TITLE
Error when manually instantiaing `message.Message` in unit tests

### ISSUE THREAD

**Issue by jceresini** [googleapis/python-pubsub#485]
I'm interested in writing a unit test for my callback function. One thing in particular I want to be able to test is the attributes of the callback message argument. As an example, I want to make sure my logic to log the `message.publish_time` and `message.attributes` is correct. 

 It appears the callback receives a `google.cloud.pubsub_v1.subscriber.message.Message`. That appears to be a wrapper for `google.pubsub_v1.PubsubMessage`.

I've tried constructing the above with the following code:

```
from google.pubsub_v1 import PubsubMessage
from google.cloud.pubsub_v1 import subscriber
from google.protobuf.timestamp_pb2 import Timestamp
from datetime import datetime, timezone

publish_time = Timestamp()
publish_time.FromDatetime(datetime.now(timezone.utc))

message_id = "test_message_id"

data = b"test message"
attributes = {"testattr1": "foo"}

pubsub_message = PubsubMessage(
    data=data, attributes=attributes, publish_time=publish_time
)

message = subscriber.message.Message(pubsub_message, 0, 0, 0)
```

But that always results in this error message:

```
Traceback (most recent call last):
  File "/x/test_pubsub_basic.py", line 18, in <module>
    message = subscriber.message.Message(pubsub_message, 0, 0, 0)
  File "/x/.venv/lib/python3.9/site-packages/google/cloud/pubsub_v1/subscriber/message.py", line 114, in __init__
    message.publish_time.seconds + message.publish_time.nanos / 1e9,
AttributeError: 'DatetimeWithNanoseconds' object has no attribute 'seconds'
```

I then noticed that in the documentation, it states not to construct the `google.cloud.pubsub_v1.subscriber.message.Message` class directly https://googleapis.dev/python/pubsub/latest/subscriber/api/message.html

> Note
> 
> This class should not be constructed directly; it is the responsibility of BasePolicy subclasses to do so.

How can I construct a `google.cloud.pubsub_v1.subscriber.message.Message` with the correct types for its attributes like `publish_time`, and `attributes`.

**Comment by plamut** [comment]
The docs for the [Message](https://googleapis.dev/python/pubsub/latest/subscriber/api/message.html) class constructor are unclear or even somewhat misleading.

> - message (`PubsubMessage`) – The message received from Pub/Sub. For performance reasons it should be the the raw protobuf message wrapped by the `PubsubMessage` class obtained through the message’s `.pb()` method.

The type of the `message` argument is said to be `PubsubMessage`, but the actual type should be the _raw_ protobuf message, i.e. the one that `PubsubMessage` wraps. That type can be obtained by calling `PubsubMessage.pb()`. The docs do mention that, but apparently in a somewhat confusing way. I think we could improve that.

Anyhow, the way to construct a `Message` is therefore as follows:
```py
>>> pubsub_message = PubsubMessage.pb()(data=data, attributes=attributes, publish_time=publish_time)
>>> message = subscriber.message.Message(pubsub_message, "0", 0, None)
>>> message
Message {
  data: b'test message'
  ordering_key: ''
  attributes: {
    "testattr1": "foo"
  }
}
```
Alternatively, if you already have a `PubsubMessage` instance, you can obtain a raw message from it thorugh the `_pb` attribute and pass the latter to `Message`:
```py
>>> pubsub_message = PubsubMessage(data=data, attributes=attributes, publish_time=publish_time)
>>> message = subscriber.message.Message(pubsub_message._pb, "0", 0, None)
>>> message
Message {
  data: b'test message'
  ordering_key: ''
  attributes: {
    "testattr1": "foo"
  }
}
```

Hope this helps!

**Comment by jceresini** [comment]
The explanation is really helpful, and I think the documentation updates in that PR will be useful for others. It might be nice to have an example showing how to unit test a callback as well.

Here's an example scenario I'm trying to prevent:

1. Existing callback code accesses a given attribute via `message.attributes['some_attribute_name']`
2. New developer adds a new attribute to the publisher, and wants to just log all of the attributes in the subscriber...
3. They see it appears to be a standard `dict` and adds a line to `json.dumps(message.attributes)`
4. Code reviewer sees a small diff, makes the same assumption, and approves code.
5. Our code ends up deployed (hopefully in a dev/nonprod environment) before noticing that it throws an exception trying to dump a `ScalarMapContainer`

In the past I've seen people test by constructing something that looks like a pubsub message, but if they make the same mistake there (setting the `message.attributes` to a `dict`) we won't catch something like this. So I'm just trying to write a unit test where I can construct an object of the same type my callback will receive in production.

Thanks again for the detailed explanation!

**Comment by plamut** [comment]
@jceresini I'm glad that it helped!

As for your application, converting messages to dicts can also be done with `google.protobuf.json_format` instead if `json.dumps()` on a possibly invalid type. Something like this:

```py
>>> from google.protobuf import json_format
...
>>> json_format.MessageToDict(pubsub_message._pb)
{'data': 'dGVzdCBtZXNzYWdl', 'attributes': {'testattr1': 'foo'}, 'publishTime': '2021-09-02T13:44:58.524030Z'}
```

Just mentioning for the reference in case you find it useful for your app.
