### ISSUE TITLE
Allow labels to be added to pubsub topic upon creation

### ISSUE THREAD

**Issue by MarkEdmondson1234** [googleapis/python-pubsub#539]
**Is your feature request related to a problem? Please describe.**
I am using the python client to create topics when a new event type comes in.  I would like to label the topics as I create them to distinguish between test, env and production environments.  I can do this in the webUI, but I can't see how to create it in the SDK.

 **Describe the solution you'd like**

Allow code like this:

```python
publisher.create_topic(name=topic_name, label = {'mykey':'myvalue'})
```

 **Describe alternatives you've considered**
I can do it manually via the web console, but it is laborious when creating a lot of topcs

**Comment by plamut** [comment]
This is already supported, although it's maybe not documented that well.

The [create_topic()](https://github.com/googleapis/python-pubsub/blob/c1b424e223fa2dc76f8d708b6786f75f43ad58e5/google/pubsub_v1/services/publisher/client.py#L416-L424) method comes from the generated part of the library. Generally, these methods accept `request` as the first argument, which is the payload that is sent to the server.

Here, the type of the request `create_topic()` expects is [pubsub.Topic](https://github.com/googleapis/python-pubsub/blob/main/google/pubsub_v1/types/pubsub.py#L112-L170) (or an equivalent dict-like object). Setting the `labels` property on the latter should do the trick:

```py
publisher.create_topic(request={"name": topic_name, "labels": [...]})
```

Sometimes it is possible to bypass the `request` object and just set the values through `kwargs`, but not all options from `request` are supported (I forgot the exact reason why this is the case).

**Comment by MarkEdmondson1234** [comment]
Ok great thanks!  Yes I did hunt high and low for some docs on it but not hard enough.  Thanks for pointing me in right direction :)
