### ISSUE TITLE
Get subscription name from a received message over that subscription

### ISSUE THREAD

**Issue by pgp** [googleapis/python-pubsub#541]
```python
def my_callback(message):
    # do whatever
    # TODO any way to retrieve subscription_name from here?
    message.ack

subscription_name = 'my_sub_name'
project_id = 'my_proj_id_123'
subscriber = pubsub_v1.SubscriberClient()
subscription_path = subscriber.subscription_path(project_id, subscription_name)
subscriber.subscribe(subscription_path, callback=my_callback)
```

As the code snippet says, is there any way to retrieve a subscription name from within a callback/message received on it?
This is useful when listening over multiple subscriptions in the same process

**Comment by plamut** [comment]
@pgp The message itself does not know anything about the subscription. Metadata can be attached to it (through the `attrs` parameter of the `publish()` method), but the publisher doesn't know either which subscriptions exists (by the very design, publishers are decoupled from subscribers).

But there's a trick - when starting a subscription, we know its name and which callback we use. We can therefore bind the subscription name to the first parameter of the callback, and use such partial function as the actual callback.
```py
import functools

def my_callback(subscription_name, message):
    print(subscription_name, message)
    message.ack()

...
subscriber.subscribe(subscription_path, callback=functools.partial(my_callback, subscription_name))
```

Does this help?

**Comment by pgp** [comment]
Yes, I already used that workaround, but since I have a lot of subscriptions / partial callbacks, having that information already present in the message object would have been better. Thanks anyway!
