### ISSUE TITLE
Open Telemetry Tracing Support

### ISSUE THREAD

**Issue by mikesmith37** [googleapis/python-pubsub#543]
Hi,

This link lead me here but I assume its now an old PR? https://github.com/googleapis/python-pubsub/pull/149

Can anyone advise of current approach for tracing processes that use google pubsub for exchanging information?

If so does this work with push subscriptions?

Thanks!
Mike S

**Comment by mikesmith37** [comment]
Perhaps setting the **traceId** message attribute as per https://dev.to/michaltalaga/tracing-logs-in-gcp-when-exchanging-message-through-pubsub-in-java-b87 ?

**Comment by plamut** [comment]
@mikesmith37 Yes, that PR is stale. Nevertheless, support for OpenTelemetry is still planned, currently the specifications are being developed. I _think_ they should be complete by the end of the year, but it is just my opinion, not an official statement.

In the meantime, what kind of tracing would you need for your project? Perhaps it might be possible to use something else until OpenTelemetry is supported.

**Comment by bgarcial** [comment]
Hi @plamut and @mikesmith37 

I see the PR https://github.com/googleapis/python-pubsub/pull/149  was or it is intended to provide tracing to a message from a publisher and how this is received in the subscriber part just to get the possibility to get track about what could be happening when things go wrong in the point the message is sent (publisher) and the message is received (subscriber) right?

In addition, you've mentioned:
>support for OpenTelemetry is still planned, currently the specifications are being developed. I think they should be complete by the end of the year, but it is just my opinion, not an official statement.

Does the python client for google pub sub actually support OTEL? or is this still on planning?

On the other hand, I see in the OTEL collector project the [Google Cloud Pub Sub exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/googlecloudpubsubexporter) and the [Google Cloud Pub Sub Receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/googlecloudpubsubreceiver) modules, how is this different from the purpose of the above here mentioned PR?

I guess under collector perspective those modules are for sending traces (already in OTEL collector) from an application perspective to a pub sub-topic (exporter) and for getting OTEL messages from a subscription (receiver), but not to trace the messages that a publisher send and a subscriber receive?

**Comment by plamut** [comment]
@bgarcial IIRC that PR was opened by a then-intern at Google,  but it was not ready to be merged yet at the time.

I unfortunately don't know if OTEL support is still planned or not, as I no longer maintain this library. Maybe @acocuzzo knows more, AFAIK she's one of the Google maintainers currently...

**Comment by acocuzzo** [comment]
@bgarcial Support is planned for this year, will continue to update this bug as progress is made

**Comment by AndreasBergmeier6176** [comment]
> @bgarcial Support is planned for this year, will continue to update this bug as progress is made

Is there a spec to have a look at?

**Comment by crossk3** [comment]
@plamut @acocuzzo @mukund-ananthu Any updates on this? I see assignment shuffling which makes me nervous...

googleapis/nodejs-pubsub has had otel support via message attributes for about [4 years now](https://github.com/googleapis/nodejs-pubsub/pull/1078/files#diff-07e7e924a70dbc2f5da9cfe0c5269c759cf55a1f7ad0f0d9dd6f402e5d056b54) and I'd love to have an officially supported way to pass parent trace context through PubSub in Python.

**Comment by petemounce** [comment]
@mukund-ananthu that is _fantastic_ news!

**Comment by mukund-ananthu** [comment]
Released as part of https://github.com/googleapis/python-pubsub/releases/tag/v2.24.0

**Comment by petemounce** [comment]
Thanks! We're eagerly trying it out now.
