### ISSUE TITLE
Pipenv Support

### ISSUE THREAD

**Issue by mboldisc** [googleapis/python-pubsub#569]
#### Environment details

  - OS type and version: macOS Big Sur 11.5.2
  - Python version: `python --version`: 3.8.2
  - pip version: `pip --version`: NA
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub`: NA

#### Steps to reproduce

  1. `pipenv shell`
  2. `pipenv install google-cloud-pubsub`

#### Information
It would be nice if pipenv worked with this library.  Right now, it gets stuck on the `Locking...` phase of pipenv (for a very long time, maybe hours).  With the debug flag `-v` turned on, it shows a ton of Google Python libraries being installed during this time.  It might be trying to rebuild the world instead of using binaries.

**Comment by acocuzzo** [comment]
Thanks for bringing this to our attention, I will look into this issue and get back to you. In the meantime, I do recommend using the library with [virtualenv](https://docs.python-guide.org/dev/virtualenvs/#lower-level-virtualenv) in place of pipenv.
