### ISSUE TITLE
Increase grpcio version to 1.51.3

### ISSUE THREAD

**Issue by acocuzzo** [googleapis/python-pubsub#609]
As per: [comment ](https://github.com/googleapis/python-pubsub/pull/435#issuecomment-1063032299)

Grpcio fails when trying to install version 1.38.1, fixed on 1.44.

Investigate upgrading this dependency.

**Comment by nathanmrtns** [comment]
Can we change this to [1.51.3](https://pypi.org/project/grpcio/1.51.3/) instead?
