### ISSUE TITLE
Occasional error: 429 received initial metadata size exceeds limit on pubsub with 21 messages of 137 bytes each

### ISSUE THREAD

**Issue by Magikzigo** [googleapis/python-pubsub#624]
Dear google team,

I am currently using Google cloud services in order to build a small personal project and while putting some pieces of pub/sub together with cloud functions, I came across some occasional errors that I am not able to troubleshoot (!) after thoroughly reading the docs.
I believe this might be useful for some other users who may encounter the same issues.

#### Environment details

  - OS type and version: Google cloud function 1st generation
  - Python version: `python --3.7`
  - pip version: `pip --version` no pip as this is cloud based
  - `google-cloud-pubsub` version: `latest version of google-cloud-pubsub launched in cloud functions'

- Other packages(requirements.txt): 
  pandas == 1.2.1
  asyncio == 3.4.3
  google-cloud-pubsub
  numpy==1.19.5
  google-cloud-bigquery==2.3.1
  google-cloud-bigquery-storage==2.0.1
  google-api-core==1.26.0
  google-cloud-core==1.4.2
  pyarrow==2.0.0
  gcsfs

#### Steps to reproduce

  1. Initiate a Pub / sub topic that is sending to a topic messages that will last for 21 minutes. There is one subscriber with retention 21 minutes for these messages. 
  2. Have a cloud scheduler running on a 20 minutes basis to initiate a cloud function
  3. Have a cloud function which is opening a streaming pull to read the files and perform some data cleaning operations as well load into Bigquery database the appended files
  4.  Run the cloud function
  5. **Sometimes** and this is why I am a bit fussed about it, there are some errors that are not linked to the code but that are linked to the online cloud function resources from pub-sub, in the form of a **429 received initial metadata size exceeds limit**. 
  6. I have checked into the docs and cannot find why I am above the limits, we are talking about 21 messages with around 137bytes of data per message

![image](https://user-images.githubusercontent.com/56662299/159611788-8b08f3b3-0363-482e-8247-6b2dfdddb2fa.png)

#### Code example

      import base64
      import pandas as pd
      import gcsfs
      from google.cloud import bigquery
      from google.api_core import retry
      from google.cloud import pubsub_v1
      import numpy as np
      from concurrent.futures import TimeoutError
      project_id = "XXX"
      subscription_id = "YYY"
      bqclient = bigquery.Client()
      #A timeout of 10s is enough for this one.
      timeout = 10.0
      
      big_markprice_df = pd.DataFrame(columns=['timestamp', 'mark_price', 'server_time'])
      
      schema_markprice = [
              bigquery.SchemaField("timestamp", bigquery.enums.SqlTypeNames.FLOAT),
              bigquery.SchemaField("mark_price", bigquery.enums.SqlTypeNames.FLOAT),
              bigquery.SchemaField("server_time", bigquery.enums.SqlTypeNames.TIMESTAMP),]
      
      def clean_markprice(df_test):
          df_test.drop(['uid'],axis=1,inplace=True)
          df_test['date'] = df_test['timestamp'] // 1000
          df_test['date'] = pd.to_datetime(df_test.date,unit='s',utc=True)
          df_test.columns = ['timestamp','mark_price','server_time']
          return df_test
      
      
      ls = []
      def callback_markprice(message: pubsub_v1.subscriber.message.Message) -> None:
          global big_markprice_df
          print(f"Received {message.data!r}.")
          # if message.attributes:
          #     print("Attributes:")
          #     for key in message.attributes:
          value = message.attributes.get('file_path')
          tmp_df = pd.read_csv(value)
          tmp_df = clean_markprice(tmp_df)
          big_markprice_df = big_markprice_df.append(tmp_df,ignore_index=True)
          big_markprice_df = big_markprice_df.drop_duplicates()
          ls.append(value)
          message.ack()      
          print(f" {len(ls)} Messages have been acked.")
          
      def load_into_bq(dataframe,schema_x,table_id):
           #write truncate to remove in case
           table_id = table_id
           job_config = bigquery.LoadJobConfig(schema=schema_x,time_partitioning=bigquery.TimePartitioning(type_=bigquery.TimePartitioningType.DAY,field="server_time",),)
           job = bqclient.load_table_from_dataframe(dataframe, table_id, job_config=job_config)  # Make an API request.
           job.result()  # Wait for the job to complete.
           table = bqclient.get_table(table_id)
           print("Loaded {} rows to table {}".format(table.num_rows, table_id))
              
      
      
      def hello_pubsub(event, context):
          """Triggered from a message on a Cloud Pub/Sub topic.
          Args:
               event (dict): Event payload.
               context (google.cloud.functions.Context): Metadata for the event.
          """
          #pubsub_message = base64.b64decode(event['data']).decode('utf-8')
          #print(pubsub_message)
          subscriber = pubsub_v1.SubscriberClient()
          subscription_path = subscriber.subscription_path(project_id, subscription_id)
          streaming_pull_future = subscriber.subscribe(subscription_path, callback=callback_markprice)
          print(f"Listening for messages on {subscription_path}..\n")
      
      Wrap subscriber in a 'with' block to automatically call close() when done.
          with subscriber:
              # When `timeout` is not set, result() will block indefinitely,
              # unless an exception is encountered first.
              try:
                  streaming_pull_future.result(timeout=timeout)
              except Exception as e:
                  print(
                      f"Listening for messages on {subscription_path} threw an exception: {e}."
                  )
                  streaming_pull_future.cancel()  # Trigger the shutdown.
                  streaming_pull_future.result()  # Block until the shutdown is complete.
          load_into_bq(big_markprice_df,schema_markprice,'XXX.ZZZ.YYY')
```

#### Stack trace
```
Exception on /_ah/push-handlers/pubsub/projects/XXX/topics/update_data_clean_bigquery [POST] Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/functions_framework/__init__.py", line 171, in view_func function(data, context) File "/workspace/main.py", line 81, in hello_pubsub streaming_pull_future.result() # Block until the shutdown is complete. File "/opt/python3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result return self.__get_result() File "/opt/python3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result raise self._exception File "/workspace/main.py", line 75, in hello_pubsub streaming_pull_future.result(timeout=timeout) File "/opt/python3.7/lib/python3.7/concurrent/futures/_base.py", line 435, in result return self.__get_result() File "/opt/python3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result raise self._exception google.api_core.exceptions.ResourceExhausted: 429 received initial metadata size exceeds limit
```

Let me know if this is enough for you to make some tests , many thanks in advance!

**Comment by Magikzigo** [comment]
Also after running these functions for a certain time I have another bug happening:
[mutex.cc : 435] RAW: Lock blocking 0x3ea040005320
and 
[mutex.cc : 1908] RAW: Check (v & (kMuWait | kMuWrWait)) != kMuWrWait failed: Lock: Mutex corrupt: waiting writer with no waiters: 0x3ea04000c7b0

Do you know why this is the case? Many thanks in advance, I suspect an environment / dependency issue

**Comment by acocuzzo** [comment]
Hi @Magikzigo,

I will look into your issue and get back to you when I have more information. Thanks so much for all the details.

**Comment by Magikzigo** [comment]
Thanks a lot in advance for the support @acocuzzo !

**Comment by pradn** [comment]
> google.api_core.exceptions.ResourceExhausted: 429 received initial metadata size exceeds limit
This exception occurs when the GRPC response's metadata is too large. It's surprising this exception is being thrown b/c the metadata should be small or nonexistent in most cases.

We did recently explicitly set the GRPC metadata size limit to 4 MB. See https://github.com/googleapis/python-pubsub/pull/623. This change may help mitigate this issue. It should be released by next week or so.

**Comment by Magikzigo** [comment]
@pradn Sure, once the patch is released I will let you know whether I still have this occasional bug. 
I checked #623 and it seems indeed that we are talking about the same issue (e.g. ack once only message with 4MB+ of meta data)

**Comment by pradn** [comment]
The fix (https://github.com/googleapis/python-pubsub/pull/623) has been released in the latest version, 2.12.0.

**Comment by Magikzigo** [comment]
Hi @pradn, well noted I will monitor until this Sunday / next Monday to check whether this is solved. 
As far as I can see I have an error rate of around 1.5-2%. 
Let me then come back at you and thanks for the support!

**Comment by Magikzigo** [comment]
Hi @pradn , after monitoring on my project, still same error rate (with 1 std dev) and the error is still appearing.
I guess the fix might not have solved it? 
Thanks in advance

**Comment by pradn** [comment]
1. Are you seeing the exact same error? "google.api_core.exceptions.ResourceExhausted: 429 received initial metadata size exceeds limit"?
1. Do you set message attributes?
2. Which grpc library version are you using? Please use the latest version.

**Comment by Magikzigo** [comment]
Thanks for the questions @pradn !
1 - ResourceExhausted: 429 received initial metadata size exceeds limit => yes the exact same one
2 - Yes I do set message attribute, I have one attribute per message which is corresponding to the file path. There is no more than one attribute per message and they are all the same.
3 - Good question, what is GRPC? 
So far I am using cloud functions and within I call the packages. 
For pub-sub I called "google-cloud-pubsub" in the requirements.txt, hence I assume that it should automatically update to the latest version?

**Comment by Magikzigo** [comment]
@pradn Do you have any feedback on this topic? Would greatly help me! Thanks a lot in advance!

**Comment by acocuzzo** [comment]
@Magikzigo Please re-open if you are still experiencing this issue, and please attach your pip freeze.
