### ISSUE TITLE
--use-keywords switch does not look to be supported

### ISSUE THREAD

**Issue by nshraddha28** [googleapis/python-pubsub#630]
The GCP public [document](https://cloud.google.com/python/docs/reference/pubsub/latest/upgrading#method-calls) mentions use of --use-keywords to generate flattened keyword parameters instead of a request dictionary. However when a customer tried to use it, it says its not supported.

Looking at the github code [history](https://github.com/googleapis/python-pubsub/commits/main/scripts/fixup_pubsub_v1_keywords.py), it was added in #208 and removed in #253. Want to confirm if the document was not updated or was this an accidental change?

Thanks!

**Comment by meredithslota** [comment]
@anguillanneuf or @pradn — do you recall the context for this change?

**Comment by nshraddha28** [comment]
Is there a reason why this flag was removed?

**Comment by pradn** [comment]
It was removed b/c the upstream code generator doesn't have this flag. The upstream version always overrides this repo's version.

To put it another way, we try to keep these scripts the same across languages and this flag was a custom flag for just this library.
