### ISSUE TITLE
shutdown error on streaming pull callback error 

### ISSUE THREAD

**Issue by kthulsidoss** [googleapis/python-pubsub#64]
Hi @plamut , i recall encountering error on streaming pull callback error  (#40) . I know this is fixed .
I received this again in using asynchronous call ? do i need to use a different version for this fix ?
Thanks
K.thulsi Doss

**Comment by plamut** [comment]
@kthulsidoss Which PubSub client version did you use?

The fix for that issue was [released in 1.3.1](https://github.com/googleapis/python-pubsub/blob/master/CHANGELOG.md#131-2020-02-28). If you PubSub client version is older than that, it needs to be upgraded, yes.

**Comment by plamut** [comment]
@kthulsidoss Any luck with resolving the issue? Did the upgrade help?

**Comment by kthulsidoss** [comment]
@plamut thanks for following it up.Due to time paucity release2 , it was decided to go with synchronous call (no problem of set result only once).

**Comment by plamut** [comment]
OK, I will close the issue then, but feel free to re-open it in case you decide to switch back to the streaming pull and still experience the problem even with the upgraded client.
