### ISSUE TITLE
Schema api not supporting pubsub emulator 

### ISSUE THREAD

**Issue by bealsao** [googleapis/python-pubsub#647]
The schema_service/client.py did not receive the fixes in this change: [297](https://github.com/googleapis/python-pubsub/pull/297)

So you receive the same errors as described in the issue: [290](https://github.com/googleapis/python-pubsub/issues/290)

I have created a fork where I added the code and verified this is all that needs to change for this to work with the pubsub emulator:
```
            emulator_host = os.environ.get("PUBSUB_EMULATOR_HOST")
            if emulator_host:
                if issubclass(Transport, type(self)._transport_registry["grpc"]):
                    channel = grpc.insecure_channel(target=emulator_host)
                else:
                    channel = grpc.aio.insecure_channel(target=emulator_host)
                Transport = functools.partial(Transport, channel=channel)
```

The fix is extremely simple as the work has already been done :)

**Comment by bealsao** [comment]
I can add a pull request if needed just let me know!

**Comment by acocuzzo** [comment]
Hi @bealsao, please see https://github.com/googleapis/google-cloud-python/blob/main/CONTRIBUTING.rst for information about contributing, and I will take a look at your PR. Thanks in advance!

**Comment by bealsao** [comment]
Hi @acocuzzo,

PR created: [651](https://github.com/googleapis/python-pubsub/pull/651)

Thanks in advance,
Cheers

**Comment by acocuzzo** [comment]
Thanks @bealsao.  Can you please sign: https://cla.developers.google.com/clas
This will allow the CI to run on your PR. Thanks!

**Comment by bealsao** [comment]
Hi @acocuzzo,

Sorry about that I fixed it up.
