### ISSUE TITLE
Monitoring batching

### ISSUE THREAD

**Issue by antoine-gallix** [googleapis/python-pubsub#65]
I've read that the pubsub client does some batching, and for what I've understood, sending of a batch is triggered once one of the three parameters is exceeded: number of messages, time since first message of the batch and size of the batch. I want to increase the speed of sending of messages to the pubsub but I don't know how to tune those parameters. Which limiting factor triggers the batches that I'm sending? How can I monitor the number of messages, size and timing of the batches the client is sending to figure this out?

**Comment by pradn** [comment]
Hey Antoine! You're correct that there's 3 conditions when a batch is "committed", meaning it is sealed off and sent to the Cloud Pub/Sub servers.

1. The batch exceeds the number of messages limit. (Enforced [here](https://github.com/googleapis/python-pubsub/blob/4b3d1797150873c77a2047f663e5d1c23962094a/google/cloud/pubsub_v1/publisher/_batch/thread.py#L353).)
2. The batch exceeds the total uncompressed byte size limit. (Enforced [here](https://github.com/googleapis/python-pubsub/blob/4b3d1797150873c77a2047f663e5d1c23962094a/google/cloud/pubsub_v1/publisher/_batch/thread.py#L353).)
3. The batch exceeds the timeout that starts the first time a message is added to it. The timer is implemented [here](https://github.com/googleapis/python-pubsub/blob/4b3d1797150873c77a2047f663e5d1c23962094a/google/cloud/pubsub_v1/publisher/client.py#L410). The same timer is used for all batches. So, an old batch and a new batch will be published when the sleep() expires.

To can set the max_messages, max_bytes, and max_latency fields in the BatchSettings object, respectively. See an example of how to set them [here](https://github.com/googleapis/python-pubsub/blob/4b3d1797150873c77a2047f663e5d1c23962094a/google/cloud/pubsub_v1/publisher/client.py#L89). The values' defaults and explanations are [here](https://github.com/googleapis/python-pubsub/blob/4b3d1797150873c77a2047f663e5d1c23962094a/google/cloud/pubsub_v1/types.py#L60).

We don't provide a public API for monitoring these metrics. You can dig into the private variables of our classes if you wish, but we don't guarantee the API will be stable.

Are you trying to optimize latency or throughput? The default max_latency is 10ms, so a message shouldn't wait longer than that to be sent to the CPS servers. You can generally get better throughput with bigger batches, so I'd recommend using (max_messages=10,000, max_size=10 * 1000 * 1000 (10MB), and max_latency = 20 (20 secs)).

Can you tell me your average message size and the rate at which you're sending them?

**Comment by antoine-gallix** [comment]
> I don't understand how increasing all three can help you understand the limiting factor? Shouldn't two be fixed and one changed to figure out the bottleneck?

It doesn't. Instead of finding the bottleneck and increasing the limiting factor, I just increase all three by the same factor. The result is the same. Whichever is the bottleneck, it will be raised.

But it doesn't matter because I realised I was probably not doing any batching to start with, because of calling for the results of the futures right away after sending them. Not doing that alone increased the base throughput by 3 orders of magnitude. Tweaking the batch settings was not much of an improvement after that.

Thanks for the answers anyway, I've learned a few things on the way.

**Comment by pradn** [comment]
future.result() blocks until the message is sent, which prevents batching. The best option is to send a large amount of messages and call future.result at the end. The only limit to storing the futures is your memory. Your machine should easily be able to handle all 500K. Glad you found the problem!
