### ISSUE TITLE
client .result() does not resolve without print()

### ISSUE THREAD

**Issue by inf3rnus** [googleapis/python-pubsub#671]
#### Environment details

  - OS type and version: Ubuntu 18.04 LTS
  - Python version: 3.7
  - pip version: 21.2.4
  - `google-cloud-pubsub` version: 2.12.0

#### Steps to reproduce

  1. Create a main.py file that executes the following:
```
from google.cloud import pubsub_v1
pub_sub_client = pubsub_v1.PublisherClient()
TOPIC = 'projects/<some project id here>/topics/<SOME TOPIC HERE>'

if __name__ == '__main__':
    pub_sub_client.publish(TOPIC, bytes(json_stringify({
            "Some message here": "1234567"
        }),'utf8')).result()
```
  2. Run `python main.py`
  3. Check Google Cloud Function logs. When checking to see if a subscribed function to the topic has been called, you *should* find that the future doesn't resolve before the process terminates. Not sure if that's truly what's going on, but the point is that the message does not seem to actually get published.

`Extra Details`

What seems to "fix" the issue, (idk if it's actually fixed, or if it's because it gives the Future() time to resolve), is storing the output of .result() in a variable and printing out the result (message id).

**Comment by acocuzzo** [comment]
Hi @inf3rnus 
You're correct that it gives the Future time to resolve. It's not necessary to print the result, you can also do the following:
```
if __name__ == '__main__':
    result = pub_sub_client.publish(TOPIC, bytes(json_stringify({
            "Some message here": "1234567"
        }),'utf8')).result()
```
the [result() function](https://github.com/googleapis/python-pubsub/blob/0a11e078660eb7213a1a323fdf701d802fb1149c/google/cloud/pubsub_v1/publisher/futures.py#L66) calls [result()](https://docs.python.org/3/library/concurrent.futures.html) on the underlying concurrent.futures.Future
