### ISSUE TITLE
How to assign labels to a topic on creation?

### ISSUE THREAD

**Issue by alexcreek** [googleapis/python-pubsub#687]
I'm trying to create a topic and assign labels to it, but I can't figure out how to do it.  I see that [gcloud pubsub topics create](https://cloud.google.com/sdk/gcloud/reference/pubsub/topics/create) supports this as well as the [gcp terraform provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic).

I've tried passing labels as the [metadata argument](https://github.com/googleapis/python-pubsub/blob/main/google/pubsub_v1/services/publisher/client.py#L500) but that doesn't work.

Does this library support assigning labels to topics?

**Comment by acocuzzo** [comment]
Hi @alexcreek 
Yes, you can assign labels when you create a topic.
When you create a topic with a call to `create_topic` on a PublishClient, you can pass additional attributes to the request:
```
publisher = pubsub_v1.PublisherClient()
    topic_path = publisher.topic_path(project_id, topic_id)
    labels_dict = {"label_key":"label_value"}
    topic = publisher.create_topic(request={"name": topic_path,"labels":labels_map})
    ```
    The function [create_topic](https://github.com/googleapis/python-pubsub/blob/24f76baeb53c53b41d0fb8b0fc68c4de7c024bac/google/pubsub_v1/services/publisher/client.py#L408)
    accepts a [Topic](https://github.com/googleapis/python-pubsub/blob/810f983f231dfde2d617cdd19de1f078ef137ed9/google/pubsub_v1/types/pubsub.py#L122)
made up of attributes that includes [labels
](https://github.com/googleapis/python-pubsub/blob/810f983f231dfde2d617cdd19de1f078ef137ed9/google/pubsub_v1/types/pubsub.py#L135).
