### ISSUE TITLE
Stack trace with google-cloud-pubsub==1.6.1 and protobuf==4.21.0

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [googleapis/python-pubsub#688]
#### Issue

While deploying Docker image to App Engine containing application that uses `google-cloud-pubsub`. This is the first time this happens, probably due to a change in protobuf. The application is a Web service running on [Gunicorn](https://gunicorn.org/), using [Flask](https://flask.palletsprojects.com) to handle PubSub pushed messages. The application itself does not instantiate the PubSub client, it just imports `google.cloud.pubsub` in a common file for all Google client libraries. The import itself seems to raise the stack trace on application startup.

#### Environment details

  - OS type and version: Debian GNU/Linux 10 (buster) - Docker image from `python:3.7-buster `
  - Python version: `Python 3.7.13`
  - pip version: `pip 22.0.4 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`
  - `google-cloud-pubsub` version: `Version: 1.6.1`

#### Steps to reproduce

  1. Install google-cloud-pubsub==1.6.1 in your Python environment
  2. Import it `from google.cloud import pubsub`

#### Code example

```python
from google.cloud import pubsub
```

#### Stack trace
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from google.cloud import pubsub
  File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/types.py", line 32, in <module>
    from google.cloud.pubsub_v1.proto import pubsub_pb2
  File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/proto/pubsub_pb2.py", line 70, in <module>
    create_key=_descriptor._internal_create_key,
  File "/usr/local/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

The link at the end does not have any information apart from the fact that new Protobuf release has breaking changes.

#### Workaround

Install explicitly an older version of Protobuf `protobuf==3.20.1`

**Comment by acocuzzo** [comment]
Hi @MiltiadisKoutsokeras, thanks for the details.

This has also caused failures in our integration tests, so I will be addressing this issue very shortly.
