### ISSUE TITLE
The `PullResponse` docstring is inaccurate

### ISSUE THREAD

**Issue by hjtran** [googleapis/python-pubsub#717]
```
class PullResponse(proto.Message):
    r"""Response for the ``Pull`` method.
    Attributes:
        received_messages (Sequence[google.pubsub_v1.types.ReceivedMessage]):
            Received Pub/Sub messages. The list will be empty if there
            are no more messages available in the backlog. For JSON, the
            response can be entirely empty. The Pub/Sub system may
            return fewer than the ``maxMessages`` requested even if
            there are more messages available in the backlog.
    """
```
The `PullResponse` docstring states that the `received_messages` ... `will be empty if there are no more messages available in the backlog.`

From my [conversation](https://googlecloud-community.slack.com/archives/C0HSQF6G7/p1654709005098599) with @kamalaboulhosn on the GCP slack, this is incorrect. Kamal mentioned that there was a doc overhaul coming that would fix it but I wonder if it might save someone else some time (we spent an embarrassing amount of dev/cpu time debugging our application which was built on this statement) if this part of the docstring was removed altogether.

**Comment by acocuzzo** [comment]
Fixed in 2.15.0
