### ISSUE TITLE
First message high latency.

### ISSUE THREAD

**Issue by adamwojt** [googleapis/python-pubsub#724]
Publishing first message(s) seem to have higher lag ~0.4sec and that lowers to 0.06 sec for consecutive messages. Messages on screenshot were published with `0.2sec` space between them so they do run in separate batch threads. I found something similar on PHP library issue page https://github.com/googleapis/google-cloud-php/issues/819. Perhaps you know how to avoid such slow requests with this python library?
 
My usecase involves propagating messages from websocket to pubsub and I noticed that after some period of inactivity the "_slow message_" will appear again.

#### Environment details

  - OS type and version: Ubuntu 22.04
  - Python version: `Python 3.9.12`
  - pip version: `pip 22.0.4`
  - `google-cloud-pubsub` version: `Version: 2.13.0`

#### Steps to reproduce

Measure time to publish.

#### Code example

```python
publisher = pubsub_v1.PublisherClient()
topic_path = publisher.topic_path(settings.pubsub_project_id, settings.pubsub_topic_id)

def callback(future, received):
    logging.info(f"published in {round(time.time()-received,2)}sec")

def add_queue_entry(data) -> int:
    received_time = time.time()
    future = publisher.publish(topic_path, data)
    future.add_done_callback(functools.partial(callback, received=received_time))
```

#### Stack trace

![image](https://user-images.githubusercontent.com/45100954/175062836-36269ccc-6c6e-4a11-a353-523753fd95f8.png)

**Comment by acocuzzo** [comment]
Hi @adamwojt 
It's likely this is a latency from the underlying opening of GRPC connection, as well as a reopening when inactive connections are closed. Our "keepalive" settings on the GRPC channel is 30s, so if 30s passes without a publish, the underlying connection will need to be reopened.

**Comment by acocuzzo** [comment]
@adamwojt Sorry for the late reply. If you are able to send empty messages to keep the connection warm, that will lower initial latency as the auth token will be refreshed. I will follow-up if I find alternatives.
