### ISSUE TITLE
Message stuck in subscription remain as undelivered

### ISSUE THREAD

**Issue by leonardara** [googleapis/python-pubsub#753]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-pubsub/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: `2.0.42-debian10`
  - Python version: `python --version`: `3.9.1`
  - pip version: `pip --version`: `22.0.3`
  - `google-cloud-pubsub` version: `pip show google-cloud-pubsub`: `2.13.4`

#### Steps to reproduce

1. Had **N** undelivered messages in a subscription;
2. Create a subscriber **SA** for this subscription with flow control `max_messages > N` which will cause all of these **N** messages be pulled by this subscriber **SA** at once;
3. Before subscriber **SA** finished processing these **N** messages, create another subscriber **SB**;
4. Subscriber **SB** will again get all of these N messages;
5. Once subscriber **SA** and **SB** finished processing, the **N** messages still stuck in the subscription **_remained as undelivered…_**

#### Code example

```python
# example
```

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by acocuzzo** [comment]
Closing as internal support case has been opened.
