### ISSUE TITLE
Pin dependencies to minor versions

### ISSUE THREAD

**Issue by kamalaboulhosn** [googleapis/python-pubsub#77]
In an attempt to minimize issues caused by bad minor releases in dependencies and to make the rollback procedure for customers easier, we should pin dependencies to a minor version. When new minor versions are released, we should increase the pinned minor version to match the new version in a PR and release a new version of the Pub/Sub client library. If there is no new code in the library, but there are new dependency minor version increments, we should release a new version at least once a month. It is fine to release at a faster cadence than that if desired. This is how things work in the Java library and in fact, the minor version increase PRs are automatically generated. Perhaps thy could be auto generated in Python as well.

**Comment by busunkim96** [comment]
I believe our Python libraries should have pins with version ranges that are as *wide as possible* given that you can only have one version of a library installed.

Very few of our customers use one google-cloud library. When a library has narrow pins, we make it more likely that customers run into the diamond dependency problem. E.g., `google-cloud-pubsub` requires google-api-core between 1.15.0 and 1.16.0, but their installed version of `google-cloud-spanner` requires `google-api-core > 1.16.0`. The customer then has to fiddle with different versions of the libraries to find some compatible combination. For Python specifically, we've had customers come to us to say that they have trouble with conflicting dependencies in Google libraries.

I am okay with pinning api-core as a temporary work-around, but don't think it should be our long-term policy given the Python language ecosystem.

**Comment by plamut** [comment]
I will also bring this topic up in the next Data & Analytics weekly.

**Comment by kamalaboulhosn** [comment]
It looks like we are going to explore other options for dealing with this issue. Closing.
