### ISSUE TITLE
Can we make samples/snitppets/publisher.py support custom message?

### ISSUE THREAD

**Issue by dutch3883** [googleapis/python-pubsub#771]
I think this snippet is officially used by GCP document to demonstrate how to interact with pubsub emulator.
I think it would be better if the example script provide can support custom pubsub message, so it can be as a publisher cli tool not only sample. I can help provide change. It shouldn't be big change.

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by acocuzzo** [comment]
This is a nice idea, thanks for the suggestion @dutch3883

**Comment by acocuzzo** [comment]
@dutch3883 This is going to remain as sample code, not a publisher cli, as the recommended cli tool would be the gcloud cli:
https://cloud.google.com/pubsub/docs/publish-receive-messages-gcloud
