### ISSUE TITLE
Add example with custom service account file to snippets

### ISSUE THREAD

**Issue by acocuzzo** [googleapis/python-pubsub#783]
something like:
```
from google.oauth2 import service_account
from google.cloud import pubsub_v1
 
scopes = ['https://www.googleapis.com/auth/cloud-platform']
sa_file = 'service-account.json'
zone = 'us-central1-a'
project_id = 'my_project_id' # Project ID, not Project Name
 
credentials = service_account.Credentials.from_service_account_file(sa_file, scopes=scopes)
 
subscriber_client = pubsub_v1.SubscriberClient(credentials=credentials)
```

**Comment by anguillanneuf** [comment]
@acocuzzo samples across gcp and languages share a standard format and shouldn't include auth, especially if this is a one-time ask. feel free to bring in @hongalex here. 

if we get a lot of requests like these, i'd suggest not update any samples but write an independent sample, if you want to surface in docs, ask the TW, but need to coordinate all 8 langs.

**Comment by acocuzzo** [comment]
Thanks!
