### ISSUE TITLE
Updating labels through update_topic throws 500 service error, but successfully updates labels

### ISSUE THREAD

**Issue by mservidio** [googleapis/python-pubsub#812]
When updating labels using the update_topic function, the call fails with the message:

`500 A service error has occurred. Please retry your request. If the error persists, please report it. [code=e8c0]`

```
topic = Topic()
topic.name = _existing_topic.name
topic.labels["the_key"] = 'the_value'
request = UpdateTopicRequest(
   topic=topic,
   update_mask={"paths": ["labels"]}
)
self.publisher.update_topic(request=request)
```

**Comment by acocuzzo** [comment]
@mservidio Did this happen only once, or does it happen every time you update a topic?
It's likely that this is a service issue and therefore please open a Cloud Support ticket.

**Comment by mservidio** [comment]
@acocuzzo - It happens often for me, will do.
