### ISSUE TITLE
Watch Request: get push notiifcation only when new mail receives

### ISSUE THREAD

**Issue by tanvi008** [googleapis/python-pubsub#822]
Hello all, 
I am trying to achieve push notification when a new mail arrives in our inbox and aslo achieved it successfully.
But can I know if we can get push notification only when new mail is received in our mailbox and not when any change occurs in the given or subscribed mailbox 
So that we can get the message list or message detail only of the new received mail.

Like is there any sort of filters as in .received or .created on watch request?

Any help is really appreciated!

**Comment by acocuzzo** [comment]
Are you asking about filtering messages on a Pub/Sub subscription? 
Please see the docs about filtering messages:
https://cloud.google.com/pubsub/docs/subscription-message-filter

**Comment by acocuzzo** [comment]
Closing as this doesn't seem to be a Pub/Sub issue.
