### ISSUE TITLE
async publish throws error when creating request body

### ISSUE THREAD

**Issue by ash2703** [googleapis/python-pubsub#831]
Tried to use the async implementation of pubsub_v1 via the async_client files. Subscriber and Ack are working correctly but the sample code given for publishing messages throws error.
#### Environment details

  - OS type and version: Debian GNU/Linux 10 (buster)
  - Python version: `Python 3.8.13`
  - pip version: `pip 22.3.1`
  - `google-cloud-pubsub` version: `2.13.7`

#### Code example

```python
publisher = pubsub_v1.PublisherAsyncClient()
topic_path = publisher.topic_path(project_id, topic_id)
encoded_message = json.dumps(message).encode("utf-8")
request = pubsub_v1.PublishRequest(
            topic=topic_path,
            messages=encoded_message
        )
```

#### Stack trace
```bash
  File "/message_broker/async_pubsub.py", line 78, in publish_message
    request = pubsub_v1.PublishRequest(
  File "/opt/conda/envs/p2p-new/lib/python3.8/site-packages/proto/message.py", line 604, in __init__
    super().__setattr__("_pb", self._meta.pb(**params))
TypeError: Parameter to MergeFrom() must be instance of same class: expected <class 'PubsubMessage'> got <class 'int'>.
```

where `message` is a dict object 

Tried running publish with data directly
```python
await publisher.publish(topic=topic_path, messages=message)
```

This results in the same error message

**Comment by Simon-HJY** [comment]
have you solved this issue? if yes, can you share the way you use?

**Comment by acocuzzo** [comment]
The async client is auto-generated and lower level than the synchronous PublisherClient, and does not have the same behavior or handwritten logic. Therefore, the samples for the PublisherClient are not directly applicable to the PublisherAsyncClient.
The synchronous client can be imported like this
`from google.cloud import pubsub_v1` and used like `pubsub_v1.PublisherClient()`, 
the publish method comes from [here](https://github.com/googleapis/python-pubsub/blob/main/google/cloud/pubsub_v1/publisher/client.py#L269)
```
    def publish(  # type: ignore[override]
        self,
        topic: str,
        data: bytes,
        ordering_key: str = "",
        retry: "OptionalRetry" = gapic_v1.method.DEFAULT,
        timeout: "types.OptionalTimeout" = gapic_v1.method.DEFAULT,
        **attrs: Union[bytes, str],
    ) -> "pubsub_v1.publisher.futures.Future":
        """Publish a single message.
...
```
As you can see, a message is passed to the `data` parameter as bytes.

On the other hand, the PublisherAsyncClient publish method is [here](https://github.com/googleapis/python-pubsub/blob/main/google/pubsub_v1/services/publisher/async_client.py#L467), and looks like this:
```
 async def publish(
        self,
        request: Optional[Union[pubsub.PublishRequest, dict]] = None,
        *,
        topic: Optional[str] = None,
        messages: Optional[MutableSequence[pubsub.PubsubMessage]] = None,
        retry: OptionalRetry = gapic_v1.method.DEFAULT,
        timeout: TimeoutType = gapic_v1.method.DEFAULT,
        metadata: Sequence[Tuple[str, str]] = (),
    ) -> pubsub.PublishResponse:
        ```
Here, the `messages` parameter is an `Optional[MutableSequence[pubsub.PubSubMessage]]`, so one would need to construct a PubSubMessage ([here](https://github.com/googleapis/python-pubsub/blob/9ff7937a7bdf6187bd1a1492e4906e3085b50bb3/google/pubsub_v1/types/pubsub.py#L225)).

**Comment by steve-marmalade** [comment]
@acocuzzo your response is very helpful to point us in the right direction, but should there be a work-item to bring the async client to feature parity with the sync client? I am trying to publish messages from an async webserver (FastAPI), which I'd expect is a pretty common use-case these days.

**Comment by steve-marmalade** [comment]
In case it's helpful to anyone else, I ultimately decided to use the synchronous `PublisherClient` and then converted the future to an `awaitable` via `asyncio.wrap_future(future)`. I think this is the easiest way to use GCP Pub/Sub in a Python async environment.
