### ISSUE TITLE
PubSub: Synchronous pull raises 504 after a few seconds if no messages available

### ISSUE THREAD

**Issue by plamut** [googleapis/python-pubsub#9]
Forked from https://github.com/googleapis/google-cloud-python/issues/7709#issuecomment-550290511.

#### Environment details

Tested with the following:
- PubSub v1.0.2
- Python 3.7
- Ubuntu 18.04.

> It is [reported](https://github.com/googleapis/google-cloud-python/issues/7709#issuecomment-554919915) that the issue does _not_ occur with in PubSub version `v0.45.0`.
~~**Update:** However, this could not be confirmed.~~
[Confirmed](https://github.com/googleapis/google-cloud-python/issues/9822#issuecomment-560374261) by @HemangChothani 

#### Steps to reproduce

1. Create a topic.
1. Create a subscription.
1. With no messages published to the topic, perform a _synchronous_ pull. 

**Actual result:**
After a few seconds a 504 DeadlineExceeded exception is raised.

**Expected result:**
Assuming that the network functions normally, there should be no error, and the `subscriber.pull()` should simply return an empty list of messages.

Mind that there is no error if the `return_immediately=True` flag is used, but the latter is set to be deprecated and should thus not be used.

### Code sample

The following script might be useful:
<details>
<summary>reproduce.py</summary>

```python
import logging
import os
import threading
import time

from google.cloud import pubsub_v1


script_dir = os.path.dirname(os.path.realpath(__file__))
log_filename = os.path.join(script_dir, "subscriber.log")

log_format = (
    "%(levelname)-8s [%(asctime)s] %(threadName)-33s "
    "[%(name)s] [%(filename)s:%(lineno)d][%(funcName)s] %(message)s"
)

logging.basicConfig(
    level=logging.DEBUG,
    format=log_format,
)

logger = logging.getLogger(__name__)

PROJECT_NAME = "my-project"
TOPIC_NAME = "my-events"
SUBSCRIPTION_NAME = f"subscription_{TOPIC_NAME}"


def main():
    subscriber = pubsub_v1.SubscriberClient()

    subscription_path = subscriber.subscription_path(PROJECT_NAME, SUBSCRIPTION_NAME)
    topic_path = subscriber.topic_path(PROJECT_NAME, TOPIC_NAME)
    # TODO: if topic does not exist, you must first create it
    subscriber.create_subscription(name=subscription_path, topic=topic_path)

    print("Starting a pull...")
    response = subscriber.pull(
        subscription_path, max_messages=3,
        # return_immediately=True
    )

    received_messages = response.received_messages

    if not received_messages:
        print("No messages received")
        return

    print("response >>", response)

    for message in response.received_messages:
        print(message.message.data.decode("utf-8"))
    
    print("Sending ACK...")
    subscriber.acknowledge(
        subscription_path, [msg.ack_id for msg in response.received_messages]
    )
    print("... ACK sent.")


if __name__ == "__main__":
    main()
```
</details>

**Comment by cesarmarroquin** [comment]
Hello, I have been running into an issue on my project when using this pub sub library.  I am seeing the same error `google.api_core.exceptions.DeadlineExceeded: 504 Deadline Exceeded` that @plamut ran into. After some research, this thread was the best thing I could find that seemed relevant, and matched the error that I ran into. 

I am using:
PubSub v1.1.0
Python 3.7
Ubuntu 18.04.

The only difference with me is that I got it after calling:
`pubsub_v1.PublisherClient().list_topics`

I would appreciate some help, I am not sure if my issue is related to this one, but the error messages do match up which led me to believe this might be the cause.

**Comment by hongalex** [comment]
Ack. Will be reverting `initial_rpc_timeout_millis` back to 25000 shortly.

**Comment by plamut** [comment]
@cesarmarroquin Listing topics is a different method on the backend, and it's likely not related to the synchronous pull. The `504 Deadline Exceeded` errors can occur randomly due to temporary network issue or other reasons.

Does the error occur often, or just every now and then when using the list topics method? Does your application otherwise work, generally speaking? Any additional info would be appreciated, thanks!

**Comment by plamut** [comment]
This should have been fixed [here](https://github.com/googleapis/python-pubsub/pull/43/files#diff-72fa69c51df7c313455a32d04bd77fbfR29) by reverting the timeout to the previous value, closing the issue.
