### ISSUE TITLE
google-api-core[grpc] dependency requirements

### ISSUE THREAD

**Issue by rosmo** [googleapis/python-pubsub#903]
I'm trying to maintain a project that a lot of dependencies between different Google Cloud API libraries, while keeping it up to date and trying to resolve conflicts between the libraries. 

It seems pubsub library has the most stringent versions requirements for `google-api-core[grpc] >= 1.34.0, <3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*`.

Given that the latest package for this is `2.8.2`, is there a need to exclude all these versions?

**Comment by acocuzzo** [comment]
The latest package for google-api-core is: 2.11.0
https://pypi.org/project/google-api-core/

Are you working on a project in python 3.6? I believe that is the only python version which requires 2.8.2

**Comment by rosmo** [comment]
Ah, must have been must my mistake. For some reason I got latest version with `google-api-core` but an old version with `google-api-core[grpc]` (the extras version), but now that I tested it against, must have been a Python version confusion.
