### ISSUE TITLE
cloud function v2 behaviour when consuming message from pubsub?

### ISSUE THREAD

**Issue by gomrinal** [googleapis/python-pubsub#915]
- Does cloud function auto-acknowledge the messages if it subscribes to the pub/sub topic? Didn't find any clear documentation on it?

**Comment by acocuzzo** [comment]
I believe this is a better question for the CloudFunctions team, but I believe in 1st generation Cloud Functions, messages are automatically acknowledged when the function is invoked, as we can see from the samples: https://cloud.google.com/functions/docs/tutorials/pubsub-1st-gen
and https://cloud.google.com/functions/docs/tutorials/pubsub#preparing_the_application
there is no mention of acking the message within the function.
However, in 2nd generation,  functions can be retried, so I would expect there messages are acked on successful invocations.
