### ISSUE TITLE
The invitation link for the slack community in README does not work.

### ISSUE THREAD

**Issue by sp1rs** [googleapis/python-pubsub#935]
The invitation link for the Slack community in README does not work.

URL: https://gcp-slack.appspot.com/
<img width="792" alt="Screenshot 2023-06-17 at 18 25 23" src="https://github.com/googleapis/python-pubsub/assets/2691397/6ba9b4fa-569a-4ab6-a01a-2be7371c7810">

**Comment by acocuzzo** [comment]
We will replace that link with:
https://stackoverflow.com/questions/tagged/google-cloud-pubsub

which is a better place for questions.
