### ISSUE TITLE
Publish Issue

### ISSUE THREAD

**Issue by atulgandhi1137** [googleapis/python-pubsub#941]
I am trying to publish some data to Pub/Sub topic, but without .result() it does not publish. It is strange because for my other pipeline, it was running fine and started seeing this issue since yesterday. I don't want to use .result() because it takes too much of time which slows down the processing.

publisher = pubsub_v1.PublisherClient()
topic_path = f'projects/project-id/topics/{topic}'
publisher.publish(topic_path, data)

**Comment by acocuzzo** [comment]
1. Can you provide more details regarding your code/application? For instance, does you application close following the publish call? 
2. If you have seen an increase in latency from the Pub/Sub service, you should file a Cloud customer support case

**Comment by acocuzzo** [comment]
Closing as no response.
